### ISSUE TITLE
Backtrace ERROR on Ubuntu 20.04

### ISSUE THREAD

**Issue by fossey1** [persepolisdm/persepolis#1001]
**System Details:**
* Operating System: Linux
* Distro(For GNU/Linux and BSD users): Ubuntu 20.04
* Desktop Environment(For GNU/Linux and BSD users): Cinnamon 
* Persepolis Version: 4.3.0

2024-08-02 15:50:02,846 - Persepolis - ERROR - Download did not start

2024-08-02 15:50:02,847 - Persepolis - ERROR - Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/persepolis/scripts/download.py", line 301, in downloadAria

    answer = server.aria2.addUri([link], aria_dict)

  File "/usr/lib/python3.8/xmlrpc/client.py", line 1109, in __call__

    return self.__send(self.__name, args)

  File "/usr/lib/python3.8/xmlrpc/client.py", line 1450, in __request

    response = self.__transport.request(

  File "/usr/lib/python3.8/xmlrpc/client.py", line 1153, in request

    return self.single_request(host, handler, request_body, verbose)

  File "/usr/lib/python3.8/xmlrpc/client.py", line 1169, in single_request

    return self.parse_response(resp)

  File "/usr/lib/python3.8/xmlrpc/client.py", line 1341, in parse_response

    return u.close()

  File "/usr/lib/python3.8/xmlrpc/client.py", line 655, in close

    raise Fault(**self._stack[0])

xmlrpc.client.Fault: <Fault 1: 'No URI to download.'>

2024-08-02 15:50:02,849 - Persepolis - ERROR - <Fault 1: 'Active Download not found for GID#ff5a24989121ece5'>

**Comment by fossey1** [comment]
This is a Persepolis problem not distro fault and should be fixed not ignored.

**Comment by alireza-amirsamimi** [comment]
This problem will be solved in the next version. Because in the next version, Aria 2 will be replaced by [Persepolis_lib](https://github.com/persepolisdm/persepolis_lib).

**Comment by sfsajid91** [comment]
> This problem will be solved in the next version. Because in the next version, Aria 2 will be replaced by [Persepolis_lib](https://github.com/persepolisdm/persepolis_lib).

Persepolis is outdated in fedora repository, current version is 4.1.0. Please update it.

**Comment by called-ishan** [comment]
> This problem will be solved in the next version. Because in the next version, Aria 2 will be replaced by [Persepolis_lib](https://github.com/persepolisdm/persepolis_lib).

Yes, please update the fedora repo version, I am having almost the same problem

**Comment by alireza-amirsamimi** [comment]
This bug was fixed with today's [pull request](https://github.com/persepolisdm/persepolis/pull/1009). We will release the new version soon.
