### ISSUE TITLE
app crash

### ISSUE THREAD

**Issue by ahmadjafari86** [persepolisdm/persepolis#1049]
**System Details:**
* Operating System: Ubuntu 22.04.5 LTS
* Distro(For GNU/Linux and BSD users): ?
* Desktop Environment(For GNU/Linux and BSD users): ? 
* Persepolis Version: 5.0.1
* How do you install Persepolis? (Repositories, source, ...)  Repositories

* _Please attach log files if crash or paste error message_

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/persepolis/scripts/persepolis.py", line 463, in main
    mainwindow = MainWindow(start_in_tray, persepolis_download_manager, persepolis_download_manager.setting)
  File "/usr/lib/python3/dist-packages/persepolis/scripts/mainwindow.py", line 1342, in __init__
    dict = download_table_dict[gid]
KeyError: 'b4684e63504c2891'

**Comment by alireza-amirsamimi** [comment]
Hello
Open terminal and execute this command.
`persepolis --clear`
