### ISSUE TITLE
کرش برنامه هنگام اجرا

### ISSUE THREAD

**Issue by mojtaba-baghban** [persepolisdm/persepolis#150]
پیغام هنگام کرش
Traceback (most recent call last):
  File "/usr/share/persepolis/persepolis", line 242, in <module>
    mainwindow = MainWindow( start_in_tray , persepolis_download_manager , persepolis_download_manager.setting )
  File "/usr/share/persepolis/mainwindow.py", line 585, in __init__
    download_info_file_list = readList(download_info_file,'string')
  File "/usr/share/persepolis/newopen.py", line 100, in readList
    dictionary = ast.literal_eval(f_string.strip())
  File "/usr/lib/python3.6/ast.py", line 48, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/usr/lib/python3.6/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing
سیستم عامل: آرچ لینوکس
نصب از طریق aur
ورژن مورد استفاده 2.3.3

**Comment by alireza-amirsamimi** [comment]
سلام
سپاس از باگ ریپورت
این باگ قبلا اطلاع داده شده بود
انشاالله در نسخه جدید برطرف میشه
برنامه رو
Reset
کنید
#95

**Comment by alireza-amirsamimi** [comment]
سلام 
این باگ در این کامیت
[Commit](https://github.com/persepolisdm/persepolis/commit/178d29e0006e777ee746926563076ae77e95e7b7)
درست شد! سپاس از اینکه اطلاع دادید . انشالله در نسخه جدید پرسپولیس این باگ رو نمیبینید :)
