### ISSUE TITLE
problem when opening pdm

### ISSUE THREAD

**Issue by ghost** [persepolisdm/persepolis#166]
Traceback (most recent call last):
  File "/usr/share/persepolis/persepolis", line 242, in <module>
    mainwindow = MainWindow( start_in_tray , persepolis_download_manager , persepolis_download_manager.setting )
  File "/usr/share/persepolis/mainwindow.py", line 585, in __init__
    download_info_file_list = readList(download_info_file,'string')
  File "/usr/share/persepolis/newopen.py", line 100, in readList
    dictionary = ast.literal_eval(f_string.strip())
  File "/usr/lib/python3.5/ast.py", line 46, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/usr/lib/python3.5/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing

**Comment by alireza-amirsamimi** [comment]
سپاس از اینکه باگ ریپورت کردید
این باگ رو روی گیت هاب حل کردم ولی هنوز آپدیت منتشر نشده
#150 

به زودی انشالله آپدیت منتشر میشه

**Comment by ghost** [comment]
از کجا فهمیدید من فارسی زبانم؟
من که انگلیسی نوشته بودم:D
اشتباه بود؟

**Comment by alireza-amirsamimi** [comment]
نه😄
از روی آدرس ایمیل گیت هابتون که محمدرضا پوینده بود
