### ISSUE TITLE
مشکل باز شدن

### ISSUE THREAD

**Issue by ghost** [persepolisdm/persepolis#185]
بعد از آپدیت باز نمیشه
`Traceback (most recent call last):
  File "./Persepolis Download Manager", line 17, in <module>
    from newopen import Open
  File "/usr/share/persepolis/newopen.py", line 21, in <module>
    import osCommands
  File "/usr/share/persepolis/osCommands.py", line 20, in <module>
    import PyQt5
ModuleNotFoundError: No module named 'PyQt5'`

**Comment by alireza-amirsamimi** [comment]
سلام
مشکل از برنامه نیست
میگه 
PyQt5
رو نصب ندارید
نصبش کنید
چه طوری برنامه رو نصب و آدیت کردید؟

**Comment by ghost** [comment]
با
sudo apt upgrade

**Comment by ghost** [comment]
اونم نصبه
python-pyqt5 is already the newest version (5.5.1+dfsg-3ubuntu4).
بعد از حذف و نصب Pyqt5 باز هم مشکل پا برجاست

**Comment by alireza-amirsamimi** [comment]
توی ترمینال بزنید
```
python3
```
بعد از اینکه وارد شل پایتون شدید این کد رو بزنید ببینید خطا میده؟

```
import PyQt5
```

**Comment by ghost** [comment]
بله خطا میده
import PyQt5
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'PyQt5'
>>>

**Comment by alireza-amirsamimi** [comment]
پس مشکل از بسته 
PyQt5
در سیستم خودتون هست . باید حلش کنید ببینید چرا پیداش نمیکنه :)

**Comment by hayyan71** [comment]
<div dir="rtl">
درود دوست عزیز

بنده به اوبونتو دسترسی ندارم. اما در توزیع هایی مانند openSUSE حتما باید قید شود که بسته برای python3 میباشد، در غیر اینصورت pyqt5 برای python2 نصب میشود. چک کنید ببینید در مخازن اوبونتو بسته ای به نام python3-pyqt5 موجود است یا خیر

**Comment by alireza-amirsamimi** [comment]
@Mosi2772 
درست میگن اسم بسته در اوبونتو
python3-pyqt5
هست

**Comment by ghost** [comment]
میدونم ولی مشکل پا برجاست بازم ممنون

**Comment by mostafaasadi** [comment]
@Mosi2772 سلام 
شما یکبار پس از آپدیت دستور 
`sudo apt install -f`
را بزنید احتمالا بسته هایی که نصب نیستند نصب می شوند 
اگر باز مشکلاتان پابرجا بود ، بصورت مستقیم بسته  
` python3-pyqt5 `
را نصب کنید
