### ISSUE TITLE
ImportError: cannot import name 'cookiejar_from_dict' 

### ISSUE THREAD

**Issue by LinArcX** [persepolisdm/persepolis#220]
سلام علی جان.
یه چند مدتی بود از پرسپولیس استفاده نکرده بودم اما پس از اجراش با خطای زیر مواجه میشم:
``` 
 ❯ persepolis                                                                                                                                                [11:52:35]
Traceback (most recent call last):        
  File "./Persepolis Download Manager", line 84, in <module>                        
    from mainwindow import MainWindow     
  File "/usr/share/persepolis/mainwindow.py", line 27, in <module>                  
    from text_queue import TextQueue      
  File "/usr/share/persepolis/text_queue.py", line 25, in <module>                  
    import spider                         
  File "/usr/share/persepolis/spider.py", line 20, in <module>                      
    from requests.cookies import cookiejar_from_dict                                
ImportError: cannot import name 'cookiejar_from_dict'  
```

**Comment by alireza-amirsamimi** [comment]
<div dir="rtl">
سلام سعید جان
ببین این بسته رو نصب داری؟
`python-requests`
و سیستمت به روز هست؟

**Comment by LinArcX** [comment]
بله علی عزیز.مشکل از به روز نبودن سیستمم بود.حل شد.
