### ISSUE TITLE
Error Open "ImportError"

### ISSUE THREAD

**Issue by Asky-M** [persepolisdm/persepolis#237]
**System Details:**
* ManjaroLinux 17.0.1
* _Traceback (most recent call last):
  File "./Persepolis Download Manager", line 84, in <module>
    from mainwindow import MainWindow
  File "/usr/share/persepolis/mainwindow.py", line 27, in <module>
    from text_queue import TextQueue
  File "/usr/share/persepolis/text_queue.py", line 25, in <module>
    import spider
  File "/usr/share/persepolis/spider.py", line 17, in <module>
    import requests
  File "/usr/lib/python3.6/site-packages/requests/__init__.py", line 60, in <module>
    from .packages.urllib3.exceptions import DependencyWarning
ImportError: cannot import name 'DependencyWarning'_

**Issue Description and steps to reproduce:**
I installed from yaourt -S persepolis.

**Comment by alireza-amirsamimi** [comment]
@Asky-M Hello
Please install python-requests package.
sudo pacman -S python-requests

**Comment by Asky-M** [comment]
thank you owner. i love you.

**Comment by alireza-amirsamimi** [comment]
@Asky-M ✋🌹 You're welcome.
