### ISSUE TITLE
The application does not open

### ISSUE THREAD

**Issue by ghost** [persepolisdm/persepolis#281]
* Operating System: ? Linux
* Distro(For GNU/Linux and BSD users): ? Ubuntu
* Desktop Environment(For GNU/Linux and BSD users): ? Gnome-shell
* Persepolis Version: ? 2.4.2
* How do you install Persepolis? (Repositories, source, ...) ppa

I have persepolis download manager more than one month but today doesn't open
```
Traceback (most recent call last):
  File "/usr/local/bin/persepolis", line 9, in <module>
    load_entry_point('persepolis==2.4.2', 'console_scripts', 'persepolis')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/usr/local/lib/python3.5/dist-packages/persepolis-2.4.2-py3.5.egg/persepolis/__main__.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/usr/local/lib/python3.5/dist-packages/persepolis-2.4.2-py3.5.egg/persepolis/scripts/persepolis.py", line 106, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/usr/local/lib/python3.5/dist-packages/persepolis-2.4.2-py3.5.egg/persepolis/scripts/bubble.py", line 19, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/usr/local/lib/python3.5/dist-packages/persepolis-2.4.2-py3.5.egg/persepolis/scripts/play.py", line 16, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/usr/local/lib/python3.5/dist-packages/persepolis-2.4.2-py3.5.egg/persepolis/scripts/logger.py", line 23, in <module>
  File "/usr/local/lib/python3.5/dist-packages/persepolis-2.4.2-py3.5.egg/persepolis/scripts/osCommands.py", line 28, in touch
FileNotFoundError: [Errno 2] No such file or directory: '/home/mostafa/.config/persepolis_download_manager/persepolisdm.log'
```

**Comment by alireza-amirsamimi** [comment]
It's weird !
Do you recently install persepolis?
Perhaps this command solves the problem
```
touch /home/mostafa/.config/persepolis_download_manager/persepolisdm.log
```

**Comment by ghost** [comment]
touch: cannot touch '/home/mostafa/.config/persepolis_download_manager/persepolisdm.log': No such file or directory

**Comment by alireza-amirsamimi** [comment]
@Mosi2772 OK!
Install the stable version of persepolis
I'll check the problem

**Comment by JafarAkhondali** [comment]
Please open a new issue if the problem exists within new version.
