### ISSUE TITLE
could not start persepolis, KeyError: 'ProxyType'

### ISSUE THREAD

**Issue by vahidvalian** [persepolisdm/persepolis#297]
*** Operating System: GNU/Linux 
* Distro: Manjaro 64bit
* Desktop Environment: KDE
* Persepolis Version: 2.4.2
* How do you install Persepolis? yaourt -S persepolis-git ** 

Desktop environment: KDE
Traceback (most recent call last):
  File "/usr/bin/persepolis", line 11, in <module>
    load_entry_point('persepolis==2.5a0', 'console_scripts', 'persepolis')()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 564, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2662, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2316, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2322, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.6/site-packages/persepolis/__main__.py", line 5, in <module>
    from persepolis.scripts import persepolis
  File "/usr/lib/python3.6/site-packages/persepolis/scripts/persepolis.py", line 90, in <module>
    from persepolis.scripts import initialization
  File "/usr/lib/python3.6/site-packages/persepolis/scripts/initialization.py", line 211, in <module>
    proxy = getProxy()
  File "/usr/lib/python3.6/site-packages/persepolis/scripts/check_proxy.py", line 48, in getProxy
    if proxysource['ProxyType'].split('\n')[0] == '1' :
KeyError: 'ProxyType'

**Comment by alireza-amirsamimi** [comment]
@vtworockman Please install stable version of persepolis.

yaourt -S persepolis

**Comment by mostafaasadi** [comment]
1f0c891
