### ISSUE TITLE
Git-version not start

### ISSUE THREAD

**Issue by varlesh** [persepolisdm/persepolis#323]
**System Details:**
* Operating System: Linux
* Distro(For GNU/Linux and BSD users): KDE Neon (based on Ubuntu 16.04)
* Desktop Environment(For GNU/Linux and BSD users): KDE
* Persepolis Version: Git
* How do you install Persepolis? From sources

* _Please attach log files if crash or paste error message_
```
persepolis
table category_db_table already exists
Desktop environment: KDE
Traceback (most recent call last):
  File "/usr/local/bin/persepolis", line 9, in <module>
    load_entry_point('persepolis==2.5a0', 'console_scripts', 'persepolis')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/usr/local/lib/python3.5/dist-packages/persepolis-2.5a0-py3.5.egg/persepolis/__main__.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/usr/local/lib/python3.5/dist-packages/persepolis-2.5a0-py3.5.egg/persepolis/scripts/persepolis.py", line 92, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/usr/local/lib/python3.5/dist-packages/persepolis-2.5a0-py3.5.egg/persepolis/scripts/initialization.py", line 182, in <module>
  File "/usr/local/lib/python3.5/dist-packages/persepolis-2.5a0-py3.5.egg/persepolis/scripts/check_proxy.py", line 48, in getProxy
KeyError: 'ProxyType'
```
**Issue Description and steps to reproduce:**
this commands not helped:
```
sudo python3 setup.py install
sudo python3 clear.py
persepolis --clear
```

**Comment by mostafaasadi** [comment]
1f0c891

**Comment by varlesh** [comment]
@mostafaasadi Your fixes worked :+1: 
![image](https://user-images.githubusercontent.com/8083855/32761466-e658b330-c90c-11e7-9feb-6803e156dd90.png)

**Comment by alireza-amirsamimi** [comment]
@varlesh 
We changed some codes in the latest commits today.
Please clone again and test again :)

**Comment by alireza-amirsamimi** [comment]
@varlesh @mostafaasadi 
Thank you :)
so I close the issue 👍
