### ISSUE TITLE
Crash if  HDD is not mounted

### ISSUE THREAD

**Issue by molaeiali** [persepolisdm/persepolis#389]
**System Details:**
* Operating System: GNU/Linux
* Distro(For GNU/Linux and BSD users): ArchLinux
* Desktop Environment(For GNU/Linux and BSD users): XFCE
* Persepolis Version: persepolis 3.0.1-1
* How do you install Persepolis? (Repositories, source, ...) AUR (not git version)

* _Please attach log files if crash or paste error message_
```
Traceback (most recent call last):
  File "/usr/bin/persepolis", line 11, in <module>
    load_entry_point('persepolis==3.0.1', 'console_scripts', 'persepolis')()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2408, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2414, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.6/site-packages/persepolis/__main__.py", line 21, in <module>
    from persepolis.scripts import persepolis
  File "/usr/lib/python3.6/site-packages/persepolis/scripts/persepolis.py", line 93, in <module>
    from persepolis.scripts import initialization
  File "/usr/lib/python3.6/site-packages/persepolis/scripts/initialization.py", line 171, in <module>
    osCommands.makeDirs(folder)
  File "/usr/lib/python3.6/site-packages/persepolis/scripts/osCommands.py", line 66, in makeDirs
    os.makedirs(folder_path, exist_ok=True)
  File "/usr/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/run/media/ali/XFS'
```

**Issue Description and steps to reproduce:**
#### Please report only one Issue (Bug or feature request or ...) in one issue! and open new Issue for another one :)

I'm using an extra HDD for my downloads, so default address is '/run/media/.....', if my HDD is not mounted when I try to open persepolis, it will crash

**Comment by alireza-amirsamimi** [comment]
I fixed this bug :)
Thanks for reporting 👍
