### ISSUE TITLE
Can not download some file

### ISSUE THREAD

**Issue by GongT** [persepolisdm/persepolis#400]
** file to download **
https://download.fedoraproject.org/pub/fedora/linux/releases/27/Workstation/x86_64/iso/Fedora-Workstation-Live-x86_64-27-1.6.iso

**System Details:**
* Operating System: Windows 10
* Persepolis Version: 3.0.1
* How do you install Persepolis? using exe from github release

```
Log File:
2018-01-20 16:15:21,487 - Persepolis Download Manager - ERROR - Download did not start

2018-01-20 16:15:21,488 - Persepolis Download Manager - ERROR - Traceback (most recent call last):

  File "persepolis\scripts\download.py", line 243, in downloadAria

  File "xmlrpc\client.py", line 1092, in __call__

  File "xmlrpc\client.py", line 1432, in __request

  File "xmlrpc\client.py", line 1134, in request

  File "xmlrpc\client.py", line 1146, in single_request

  File "xmlrpc\client.py", line 1252, in send_request

  File "http\client.py", line 975, in putrequest

http.client.CannotSendRequest: Request-sent



2018-01-20 16:15:21,615 - Persepolis Download Manager - ERROR - Download failed - GID : 192078f9a3357d54/nMessage : Error

2018-01-20 16:15:36,739 - Persepolis Download Manager - INFO - 192078f9a3357d54 Starts

2018-01-20 16:15:38,017 - Persepolis Download Manager - ERROR - Download failed - GID : 192078f9a3357d54/nMessage : Network problem has occurred. cause:A socket operation was attempted to an unreachable network.
```

**Issue Description and steps to reproduce:**
It works well to download other files. but not this one.    
I can download it with my browser.

**Comment by alireza-amirsamimi** [comment]
Did you try to add link with persepolis's browser [extension](https://github.com/persepolisdm/persepolis/wiki/Home-en#extensions)?
