### ISSUE TITLE
persepolisdm not open!!!!! Please help

### ISSUE THREAD

**Issue by emrekndl** [persepolisdm/persepolis#450]
**System Details:**
* Operating System: Gnu/Linux
* Distro(For GNU/Linux and BSD users): Debian 9
* Desktop Environment(For GNU/Linux and BSD users): Gnome
* Persepolis Version: 3.0.1.0
* How do you install Persepolis? (Repositories, source, ...)
sudo add-apt-repository ppa:persepolis/ppa
sudo apt update
sudo apt install persepolis

* _Please attach log files if crash or paste error message_
```emre@deb:~$ persepolis
Traceback (most recent call last):
  File "/usr/local/bin/persepolis", line 11, in <module>
    load_entry_point('persepolis==3.0.1', 'console_scripts', 'persepolis')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2408, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2414, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "build/bdist.linux-x86_64/egg/persepolis/__main__.py", line 20, in <module>
  File "build/bdist.linux-x86_64/egg/persepolis/scripts/persepolis.py", line 32, in <module>
ImportError: No module named scripts
```
**Issue Description and steps to reproduce:**

**Comment by alireza-amirsamimi** [comment]
Hello
It's installed in wrong path! Persepolis is python3 module but it's installed as python2 module.
Uninstall persepolis and remove the repository, too. Use this [instruction](https://github.com/persepolisdm/persepolis/wiki/debian-installation-instruction) for installation :)

**Comment by emrekndl** [comment]
```root@deb:/home/emre# sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys AC4E8D9CDCB0980D
Executing: /tmp/apt-key-gpghome.Y9J32qI5ra/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys AC4E8D9CDCB0980D
gpg: failed to start the dirmngr '/usr/bin/dirmngr': No such file or directory
gpg: connecting dirmngr at '/tmp/apt-key-gpghome.Y9J32qI5ra/S.dirmngr' failed: No such file or directory
gpg: keyserver receive failed: No dirmngr
root@deb:/home/emre# 
```

**Comment by mostafaasadi** [comment]
Hi 
please install **dirmngr** first
` sudo apt-get install dirmngr`
then add key and repo again

**Comment by emrekndl** [comment]
installed dirmngr, added key.installed persepolis but not open same error
```emre@deb:~$ persepolis
Traceback (most recent call last):
  File "/usr/local/bin/persepolis", line 11, in <module>
    load_entry_point('persepolis==3.0.1', 'console_scripts', 'persepolis')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2408, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2414, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "build/bdist.linux-x86_64/egg/persepolis/__main__.py", line 20, in <module>
  File "build/bdist.linux-x86_64/egg/persepolis/scripts/persepolis.py", line 32, in <module>
ImportError: No module named scripts
```

**Comment by Hitaro** [comment]
Please edit your posts and use ![screenshot_20180228_231216](https://user-images.githubusercontent.com/18015032/36809314-d47f587a-1cdc-11e8-92ca-e2181d65558a.png) for codes.

**Comment by mostafaasadi** [comment]
Hi 
last night I tested persepolis on debian stretch, all things were perfect.
in your case according to your error , persepolis has installed under python2 while it should installed under python3.
so I think there is a problem with your system and I suggest you to [install from source](https://github.com/persepolisdm/persepolis/wiki/git-installation-instruction).
