### ISSUE TITLE
Crash on touch()

### ISSUE THREAD

**Issue by hedayat** [persepolisdm/persepolis#462]
This bug is reported against Fedora by a user (https://bugzilla.redhat.com/show_bug.cgi?id=1556960):

**System Details:**
* Operating System: GNU/Linux
* Distro(For GNU/Linux and BSD users): Fedora
* Desktop Environment(For GNU/Linux and BSD users): I don't know (I'm not the reporter)
* Persepolis Version: 3.0.1
* How do you install Persepolis? Repository

cmdline:        /usr/bin/python3 /usr/bin/persepolis
crash_function: touch
exception_type: FileNotFoundError
executable:     /usr/bin/persepolis
kernel:         4.15.7-300.fc27.x86_64
runlevel:       N 5
type:           Python3
uid:            1000
```
Truncated backtrace:
osCommands.py:26:touch:FileNotFoundError: [Errno 2] No such file or directory: '/home/sajjad/.config/persepolis_download_manager/persepolisdm.log'

Traceback (most recent call last):
  File "/usr/bin/persepolis", line 11, in <module>
    load_entry_point('persepolis==3.0.1', 'console_scripts', 'persepolis')()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2749, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2402, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2408, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.6/site-packages/persepolis/__main__.py", line 21, in <module>
    from persepolis.scripts import persepolis
  File "/usr/lib/python3.6/site-packages/persepolis/scripts/persepolis.py", line 110, in <module>
    from persepolis.scripts.bubble import notifySend
  File "/usr/lib/python3.6/site-packages/persepolis/scripts/bubble.py", line 18, in <module>
    from persepolis.scripts.play import playNotification
  File "/usr/lib/python3.6/site-packages/persepolis/scripts/play.py", line 16, in <module>
    from persepolis.scripts import logger
  File "/usr/lib/python3.6/site-packages/persepolis/scripts/logger.py", line 41, in <module>
    osCommands.touch(log_file)
  File "/usr/lib/python3.6/site-packages/persepolis/scripts/osCommands.py", line 26, in touch
    f = open(file_path, 'w')
FileNotFoundError: [Errno 2] No such file or directory: '/home/sajjad/.config/persepolis_download_manager/persepolisdm.log'

Local variables in innermost frame:
file_path: '/home/sajjad/.config/persepolis_download_manager/persepolisdm.log'
```

**Comment by alireza-amirsamimi** [comment]
Perhaps user changed some thing manually.
Try this code in terminal
```touch ~/.config/persepolis_download_manager/persepolisdm.log ```

**Comment by hedayat** [comment]
I told him to come here to provide more info. Thanks.

**Comment by sajjads24** [comment]
[persepolisdm.log](https://github.com/persepolisdm/persepolis/files/1824521/persepolisdm.log)
i am can not download many website ...
how fix it ?

**Comment by alireza-amirsamimi** [comment]
Do you use tor or ... ?
Can you tell me link of sites?
Do you use persepolis browser extension?
Thanks for sending the log files.

**Comment by sajjads24** [comment]
Do you use tor or ... ?No
Can you tell me link of sites?Yes , for example www.bmi.ir or www.github.com , ...
Do you use persepolis browser extension?Yes
