### ISSUE TITLE
__init__(): properties.py:190:__init__:TypeError: 'QDateTimeEdit' object is not callable 

### ISSUE THREAD

**Issue by hedayat** [persepolisdm/persepolis#475]
**System Details:**
* Operating System: ?GNU/Linux
* Distro(For GNU/Linux and BSD users): ? Fedora
* Desktop Environment(For GNU/Linux and BSD users): ?
* Persepolis Version: ?3.0.1
* How do you install Persepolis? (Repositories, source, ...) repository

Version-Release number of selected component:
persepolis-3.0.1-3.fc27

```
Additional info:
reporter:       libreport-2.9.3
cmdline:        persepolis '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' ''
crash_function: __init__
exception_type: TypeError
executable:     /usr/bin/persepolis
kernel:         4.15.10-300.fc27.x86_64
runlevel:       N 5
type:           Python3
uid:            1000

Truncated backtrace:
properties.py:190:__init__:TypeError: 'QDateTimeEdit' object is not callable

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/persepolis/scripts/mainwindow.py", line 2075, in propertiesButtonPressed
    self.propertiesCallback, gid, self.persepolis_setting, self)
  File "/usr/lib/python3.6/site-packages/persepolis/scripts/properties.py", line 190, in __init__
    self.end_time_qDateTimeEdit(q_time)
TypeError: 'QDateTimeEdit' object is not callable

Local variables in innermost frame:
q_time: PyQt5.QtCore.QTime(7, 50)
minute: '50'
hour: '7'
limit: '0'
current_category_index: 1
queue: 'Scheduled Downloads'
categories_list: ['All Downloads', 'Single Downloads', 'Scheduled Downloads']
status: 'stopped'
key: 'after_download'
parent: <persepolis.scripts.mainwindow.MainWindow object at 0x7f2297a45c18>
persepolis_setting: <PyQt5.QtCore.QSettings object at 0x7f22a0e88558>
gid: '2e940650c7a9ba9d'
callback: <bound method MainWindow.propertiesCallback of <persepolis.scripts.mainwindow.MainWindow object at 0x7f2297a45c18>>
self: <persepolis.scripts.properties.PropertiesWindow object at 0x7f227c0dbf78>
__class__: <class 'persepolis.scripts.properties.PropertiesWindow'>

```

**Comment by alireza-amirsamimi** [comment]
Thanks for reporting :+1:

**Comment by hedayat** [comment]
Thanks :)
