### ISSUE TITLE
crash in arch

### ISSUE THREAD

**Issue by sjmars** [persepolisdm/persepolis#476]
```Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/persepolis-3.0.1-py3.6.egg/persepolis/scripts/persepolis.py", line 432, in main
    mainwindow = MainWindow(start_in_tray, persepolis_download_manager, persepolis_download_manager.setting)
  File "/usr/lib/python3.6/site-packages/persepolis-3.0.1-py3.6.egg/persepolis/scripts/mainwindow.py", line 891, in __init__
    self.persepolis_db.setDBTablesToDefaultValue()
  File "/usr/lib/python3.6/site-packages/persepolis-3.0.1-py3.6.egg/persepolis/scripts/data_base.py", line 1119, in setDBTablesToDefaultValue
    self.persepolis_db_connection.commit()
sqlite3.OperationalError: database or disk is full```

**Comment by alireza-amirsamimi** [comment]
Hi
The error message says that your disk space is full or database is full.
I guess your hard disk have not enough space.
