### ISSUE TITLE
ubuntu 17.10 package problem

### ISSUE THREAD

**Issue by ghost** [persepolisdm/persepolis#479]
new version 3.10 doesn't work on ubuntu 17.10

Error message
------------------------
```bash
Traceback (most recent call last):
  File "/usr/bin/persepolis", line 11, in <module>
    load_entry_point('persepolis==3.1.0', 'console_scripts', 'persepolis')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 564, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2662, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2316, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2322, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/persepolis/__main__.py", line 20, in <module>
    from persepolis.scripts import persepolis
  File "/usr/lib/python3/dist-packages/persepolis/scripts/persepolis.py", line 88, in <module>
    from persepolis.scripts.mainwindow import MainWindow
  File "/usr/lib/python3/dist-packages/persepolis/scripts/mainwindow.py", line 62, in <module>
    from persepolis.scripts.video_finder_addlink import VideoFinderAddLink
  File "/usr/lib/python3/dist-packages/persepolis/scripts/video_finder_addlink.py", line 26, in <module>
    import youtube_dl
ModuleNotFoundError: No module named 'youtube_dl'

```

**Comment by alireza-amirsamimi** [comment]
How do you install this

**Comment by ghost** [comment]
simple upgrade from repo `http://ppa.launchpad.net/persepolis/ppa/ubuntu`

**Comment by alireza-amirsamimi** [comment]
Thanks for reporting.
For solving the issue, install youtube-dl package.

**Comment by mostafaasadi** [comment]
Hi @Mosi2772 
can you test after installing youtube-dl from repo ?

**Comment by ghost** [comment]
still doesn't work

**Comment by alireza-amirsamimi** [comment]
@Mosi2772 What is the error message now?

**Comment by ghost** [comment]
after using `sudo pip install youtube-dl`
now I can use youtube-dl in terminal directly
but Persepolis still throw the same error

**Comment by alireza-amirsamimi** [comment]
@Mosi2772 Please install youtube-dl from Ubuntu's repository.

**Comment by ghost** [comment]
```bash
sudo apt install persepolis 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  youtube-dl
The following NEW packages will be installed:
  persepolis youtube-dl
0 upgraded, 2 newly installed, 0 to remove and 1 not upgraded.
Need to get 1,148 kB of archives.
After this operation, 7,464 kB of additional disk space will be used.
Do you want to continue? [Y/n] 
Get:1 http://ppa.launchpad.net/rvm/smplayer/ubuntu artful/main amd64 youtube-dl all 1:2018.03.10-1~webupd8~artful0 [943 kB]
Get:2 http://ppa.launchpad.net/persepolis/ppa/ubuntu artful/main amd64 persepolis all 3.1.0.0 [205 kB]
Fetched 1,148 kB in 16s (67.7 kB/s)                                            
Selecting previously unselected package youtube-dl.
(Reading database ... 290782 files and directories currently installed.)
Preparing to unpack .../youtube-dl_1%3a2018.03.10-1~webupd8~artful0_all.deb ...
Unpacking youtube-dl (1:2018.03.10-1~webupd8~artful0) ...
Selecting previously unselected package persepolis.
Preparing to unpack .../persepolis_3.1.0.0_all.deb ...
Unpacking persepolis (3.1.0.0) ...
Processing triggers for mime-support (3.60ubuntu1) ...
Processing triggers for desktop-file-utils (0.23-1ubuntu3) ...
Setting up youtube-dl (1:2018.03.10-1~webupd8~artful0) ...
Processing triggers for bamfdaemon (0.5.3+17.10.20170810-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for man-db (2.7.6.1-2) ...
Processing triggers for gnome-menus (3.13.3-6ubuntu5) ...
Setting up persepolis (3.1.0.0) ...
mostafa@mostafa-Lenovo-Z50-70:~$ persepolis 
Traceback (most recent call last):
  File "/usr/bin/persepolis", line 11, in <module>
    load_entry_point('persepolis==3.1.0', 'console_scripts', 'persepolis')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 564, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2662, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2316, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2322, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/persepolis/__main__.py", line 20, in <module>
    from persepolis.scripts import persepolis
  File "/usr/lib/python3/dist-packages/persepolis/scripts/persepolis.py", line 88, in <module>
    from persepolis.scripts.mainwindow import MainWindow
  File "/usr/lib/python3/dist-packages/persepolis/scripts/mainwindow.py", line 62, in <module>
    from persepolis.scripts.video_finder_addlink import VideoFinderAddLink
  File "/usr/lib/python3/dist-packages/persepolis/scripts/video_finder_addlink.py", line 26, in <module>
    import youtube_dl
ModuleNotFoundError: No module named 'youtube_dl'

```

**Comment by alireza-amirsamimi** [comment]
@Mosi2772 Please remove unofficial youtube-dl repository and uninstall it. Then uninstall youtube that you installed with pip. Then install youtube-dl from Ubuntu's official repository.

sudo apt install youtube-dl

**Comment by ghost** [comment]
I don't know about python but seems names are different
` youtube-dl`
`'youtube_dl'`

**Comment by alireza-amirsamimi** [comment]
@Mosi2772 youtube-dl package in Ubuntu installs youtube_dl module in Python 3

**Comment by ghost** [comment]
```bash
sudo apt purge youtube-dl
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  adwaita-qt aria2 libqt5designer5 libqt5help5 libqt5test5 libqt5xml5
  python3-psutil python3-pyqt5 python3-setproctitle python3-sip rtmpdump
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  persepolis* youtube-dl*
0 upgraded, 0 newly installed, 2 to remove and 1 not upgraded.
After this operation, 7,464 kB disk space will be freed.
Do you want to continue? [Y/n] 
(Reading database ... 291646 files and directories currently installed.)
Removing persepolis (3.1.0.0) ...
Removing youtube-dl (1:2018.03.10-1~webupd8~artful0) ...
Processing triggers for mime-support (3.60ubuntu1) ...
Processing triggers for desktop-file-utils (0.23-1ubuntu3) ...
Processing triggers for bamfdaemon (0.5.3+17.10.20170810-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for man-db (2.7.6.1-2) ...
Processing triggers for gnome-menus (3.13.3-6ubuntu5) ...
(Reading database ... 290785 files and directories currently installed.)
Purging configuration files for youtube-dl (1:2018.03.10-1~webupd8~artful0) ...
mostafa@mostafa-Lenovo-Z50-70:~$ sudo apt install persepolis 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  youtube-dl
The following NEW packages will be installed:
  persepolis youtube-dl
0 upgraded, 2 newly installed, 0 to remove and 1 not upgraded.
Need to get 1,148 kB of archives.
After this operation, 7,464 kB of additional disk space will be used.
Do you want to continue? [Y/n] 
Get:1 http://ppa.launchpad.net/rvm/smplayer/ubuntu artful/main amd64 youtube-dl all 1:2018.03.10-1~webupd8~artful0 [943 kB]
Get:2 http://ppa.launchpad.net/persepolis/ppa/ubuntu artful/main amd64 persepolis all 3.1.0.0 [205 kB]
Fetched 1,148 kB in 14s (78.7 kB/s)                                            
Selecting previously unselected package youtube-dl.
(Reading database ... 290782 files and directories currently installed.)
Preparing to unpack .../youtube-dl_1%3a2018.03.10-1~webupd8~artful0_all.deb ...
Unpacking youtube-dl (1:2018.03.10-1~webupd8~artful0) ...
Selecting previously unselected package persepolis.
Preparing to unpack .../persepolis_3.1.0.0_all.deb ...
Unpacking persepolis (3.1.0.0) ...
Processing triggers for mime-support (3.60ubuntu1) ...
Processing triggers for desktop-file-utils (0.23-1ubuntu3) ...
Setting up youtube-dl (1:2018.03.10-1~webupd8~artful0) ...
Processing triggers for bamfdaemon (0.5.3+17.10.20170810-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for man-db (2.7.6.1-2) ...
Processing triggers for gnome-menus (3.13.3-6ubuntu5) ...
Setting up persepolis (3.1.0.0) ...
mostafa@mostafa-Lenovo-Z50-70:~$ persepolis 
Traceback (most recent call last):
  File "/usr/bin/persepolis", line 11, in <module>
    load_entry_point('persepolis==3.1.0', 'console_scripts', 'persepolis')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 564, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2662, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2316, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2322, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/persepolis/__main__.py", line 20, in <module>
    from persepolis.scripts import persepolis
  File "/usr/lib/python3/dist-packages/persepolis/scripts/persepolis.py", line 88, in <module>
    from persepolis.scripts.mainwindow import MainWindow
  File "/usr/lib/python3/dist-packages/persepolis/scripts/mainwindow.py", line 62, in <module>
    from persepolis.scripts.video_finder_addlink import VideoFinderAddLink
  File "/usr/lib/python3/dist-packages/persepolis/scripts/video_finder_addlink.py", line 26, in <module>
    import youtube_dl
ModuleNotFoundError: No module named 'youtube_dl'

```

**Comment by ghost** [comment]
it's work on python 2 but doesn't work on python 3
```python
python
Python 2.7.14 (default, Sep 23 2017, 22:06:14) 
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import youtube_dl
>>> exit()
mostafa@mostafa-Lenovo-Z50-70:~$ python3
Python 3.6.3 (default, Oct  3 2017, 21:45:48) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import youtube_dl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'youtube_dl'
>>> exit()

```

**Comment by alireza-amirsamimi** [comment]
@Mosi2772 Try
sudo pip3 install youtube-dl

**Comment by ghost** [comment]
works!
`sudo apt install python3-pip`
`sudo pip3 install youtube-dl`

**Comment by alireza-amirsamimi** [comment]
@Mosi2772 Nice👌
