### ISSUE TITLE
بالا نیامدن پرسپولیس 

### ISSUE THREAD

**Issue by h420** [persepolisdm/persepolis#482]
**System Details:**
* Operating System: ?linux
* Distro(For GNU/Linux and BSD users): ?fedora 27
* Desktop Environment(For GNU/Linux and BSD users): ?gnome 3.26.2
* Persepolis Version: ?3.0.1
* How do you install Persepolis? (Repositories, source, ...)Repositories

سلام و تبریک سال نو
نرم افزار پرسدولیس رو در ترمینال اجرا کردم خطای زیر رو میده لطفا راهنمایی کنید چکار کنم با تشکر از شما 
```
[hosein@besat ~]$ persepolis
Traceback (most recent call last):
  File "/usr/bin/persepolis", line 11, in <module>
    load_entry_point('persepolis==3.0.1', 'console_scripts', 'persepolis')()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2749, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2402, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2408, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.6/site-packages/persepolis/__main__.py", line 21, in <module>
    from persepolis.scripts import persepolis
  File "/usr/lib/python3.6/site-packages/persepolis/scripts/persepolis.py", line 93, in <module>
    from persepolis.scripts import initialization
  File "/usr/lib/python3.6/site-packages/persepolis/scripts/initialization.py", line 171, in <module>
    osCommands.makeDirs(folder)
  File "/usr/lib/python3.6/site-packages/persepolis/scripts/osCommands.py", line 66, in makeDirs
    os.makedirs(folder_path, exist_ok=True)
  File "/usr/lib64/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib64/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib64/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib64/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/run/media'

```

**Comment by alireza-amirsamimi** [comment]
Hello
Use english language here, Please.
You have permission error. `PermissionError: [Errno 13] Permission denied: '/run/media'`
Persepolis couldn't make any directory on your home path.

**Comment by h420** [comment]
Thank you
Please help me solve the problem ?

**Comment by mostafaasadi** [comment]
Hi @h420 
give me : 
`ls -lrth /home/`
`ls -lrth ~/.persepolis`
`ls -lrth /run/media`

**Comment by h420** [comment]
[hosein@besat ~]$ ls -lrth /home/
total 4.0K
drwx------. 42 hosein hosein 4.0K Apr  1 21:08 hosein
[hosein@besat ~]$ ls -lrth ~/.persepolis
total 0
[hosein@besat ~]$ ls -lrth /run/media
ls: cannot access '/run/media': No such file or directory

**Comment by mostafaasadi** [comment]
it seems good
recheck persepolis after `persepolis --clear`

**Comment by h420** [comment]
upgrade to version 3.1 Now it's running. Thank you for your help
