### ISSUE TITLE
ModuleNotFoundError: No module named 'youtube_dl'

### ISSUE THREAD

**Issue by msajadi832** [persepolisdm/persepolis#484]
**System Details:**
* Operating System: GNU/Linux
* Distro(For GNU/Linux and BSD users): Ubuntu 17.10
* Desktop Environment(For GNU/Linux and BSD users): Gnome
* Persepolis Version: 3.1.0
* How do you install Persepolis? Repository

* _Please attach log files if crash or paste error message_

**Issue Description and steps to reproduce:**
When run from terminal:

`
$ persepolis 

Traceback (most recent call last):

  File "/usr/bin/persepolis", line 11, in <module>
    load_entry_point('persepolis==3.1.0', 'console_scripts', 'persepolis')()

  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 564, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)

  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2662, in load_entry_point
    return ep.load()

  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2316, in load
    return self.resolve()

  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2322, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)

  File "/usr/lib/python3/dist-packages/persepolis/__main__.py", line 20, in <module>
    from persepolis.scripts import persepolis

  File "/usr/lib/python3/dist-packages/persepolis/scripts/persepolis.py", line 88, in <module>
    from persepolis.scripts.mainwindow import MainWindow

  File "/usr/lib/python3/dist-packages/persepolis/scripts/mainwindow.py", line 62, in <module>
    from persepolis.scripts.video_finder_addlink import VideoFinderAddLink

  File "/usr/lib/python3/dist-packages/persepolis/scripts/video_finder_addlink.py", line 26, in <module>
    import youtube_dl

ModuleNotFoundError: No module named 'youtube_dl'
`

But youtube_db is installed:
`$ youtube-dl --version
2018.03.10
`

**Comment by msajadi832** [comment]
install older version of youtube-dl (2017.09.24) fix problem.
youtube-dl version 2018.03.10 is very new!!

**Comment by acosonic** [comment]
This is not a good solution... Its still an error

**Comment by acosonic** [comment]
This actually fixed problem for me

```
sudo apt install python3-pip 
sudo pip3 install youtube-dl
```

After fixing missing pip3 command 
by following this
[https://superuser.com/questions/769920/python3-pip-installed-but-pip3-command-not-found](https://superuser.com/questions/769920/python3-pip-installed-but-pip3-command-not-found)
