### ISSUE TITLE
Can't run the app from the last update (3.10 version)

### ISSUE THREAD

**Issue by hoseinzamani** [persepolisdm/persepolis#489]
**System Details:**
* Operating System: GNU/Linux
* Distro(For GNU/Linux and BSD users): Ubuntu 17.10
* Desktop Environment(For GNU/Linux and BSD users): Gnome
* Persepolis Version: 3.10
* How do you install Persepolis? 
    sudo add-apt-repository ppa:persepolis/ppa
    sudo apt-get update
    sudo apt-get install persepolis

**Issue Description and steps to reproduce:**
I can't run the app after the last update.
It used to work fine before that.
I've tried to re-install the app but nothing has changed.

**Comment by alireza-amirsamimi** [comment]
Hello
Run `persepolis` from terminal and paste the error message here.

**Comment by alireza-amirsamimi** [comment]
@hoseinzamani Hello
Run Persepolis from terminal and paste error message here.

**Comment by hoseinzamani** [comment]
Traceback (most recent call last):
File "/usr/bin/persepolis", line 11, in <module>
load_entry_point('persepolis==3.1.0', 'console_scripts', 'persepolis')()
File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 564, in load_entry_point
return get_distribution(dist).load_entry_point(group, name)
File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2662, in load_entry_point
return ep.load()
File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2316, in load
return self.resolve()
File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2322, in resolve
module = __import__(self.module_name, fromlist=['__name__'], level=0)
File "/usr/lib/python3/dist-packages/persepolis/__main__.py", line 20, in <module>
from persepolis.scripts import persepolis
File "/usr/lib/python3/dist-packages/persepolis/scripts/persepolis.py", line 88, in <module>
from persepolis.scripts.mainwindow import MainWindow
File "/usr/lib/python3/dist-packages/persepolis/scripts/mainwindow.py", line 62, in <module>
from persepolis.scripts.video_finder_addlink import VideoFinderAddLink
File "/usr/lib/python3/dist-packages/persepolis/scripts/video_finder_addlink.py", line 26, in <module>
import youtube_dl
ModuleNotFoundError: No module named 'youtube_dl'

**Comment by alireza-amirsamimi** [comment]
Youtube-dl is not installed.
Try this codes abd paste the output please.
`sudo apt install youtube-dl`
`youtube-dl --version`

**Comment by hoseinzamani** [comment]
2018.03.03

**Comment by alireza-amirsamimi** [comment]
@hoseinzamani sudo apt install python3-pip sudo pip3 install youtube-dl

**Comment by alireza-amirsamimi** [comment]
`sudo apt install python3-pip `
`sudo pip3 install youtube-dl`

**Comment by hoseinzamani** [comment]
Thanks! 
The issue has been solved.
