### ISSUE TITLE
Error , Bug!

### ISSUE THREAD

**Issue by QuestionPython** [persepolisdm/persepolis#507]
**System Details:**
* Operating System: GNU/Linux
* Desktop Environment(For GNU/Linux and BSD users): Gnome
* Persepolis Version: 3.1.0

$ persepolis --version
---------
`Persepolis Download Manager 3.1.0`

What Happen?
---------------
at the first , its open.
and i add a link in list!
after start downloading... its hang and stop!
*currently persepolis window app never not open!*

$ persepolis 
--------
```
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/persepolis/scripts/mainwindow.py", line 230, in run
    gid_list, download_status_list = download.tellActive()
  File "/usr/lib/python3.4/site-packages/persepolis/scripts/download.py", line 302, in tellActive
    converted_info_dict = convertDownloadInformation(dict)
  File "/usr/lib/python3.4/site-packages/persepolis/scripts/download.py", line 424, in convertDownloadInformation
    size_str = humanReadbleSize(file_size)
  File "/usr/lib/python3.4/site-packages/persepolis/scripts/useful_tools.py", line 72, in humanReadbleSize
    return str(round(size, p)) +' '+ labels[i]
TypeError: 'NoneType' object cannot be interpreted as an integer
Aborted (core dumped)
```

**Comment by alireza-amirsamimi** [comment]
@questionpython Hello
Your problem is related to your Python version. Python 3.4 is very old. Persepolis needs newer version of Python 3. For example Python 3.6 or newer.
