### ISSUE TITLE
errore add ppa persepolis

### ISSUE THREAD

**Issue by Pakrohk** [persepolisdm/persepolis#524]
**System Details:**
* Operating System: Gnu/Linux
* Distro(For GNU/Linux and BSD users): Deepin
* Desktop Environment(For GNU/Linux and BSD users): DDE
* Persepolis Version: laste
* How do you install Persepolis? (Repositories, source, ...)
Repositories

```Persepolis download manager is a GUI for aria2
website: https://persepolisdm.github.io
github: https://github.com/persepolisdm/persepolis
 More info: https://launchpad.net/~persepolis/+archive/ubuntu/ppa
Press [ENTER] to continue or ctrl-c to cancel adding it

gpg: keybox '/tmp/tmpeuii71ac/pubring.gpg' created
gpg: /tmp/tmpeuii71ac/trustdb.gpg: trustdb created
gpg: key AC4E8D9CDCB0980D: public key "Launchpad PPA for Persepolis Download Manager" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: no valid OpenPGP data found.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 688, in addkey_func
    func(**kwargs)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 386, in add_key
    return apsk.add_ppa_signing_key()
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 273, in add_ppa_signing_key
    cleanup(tmp_keyring_dir)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 234, in cleanup
    shutil.rmtree(tmp_keyring_dir)
  File "/usr/lib/python3.5/shutil.py", line 480, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib/python3.5/shutil.py", line 438, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/lib/python3.5/shutil.py", line 436, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
FileNotFoundError: [Errno 2] No such file or directory: 'S.gpg-agent.browser'
```

**Comment by iman-salmani** [comment]
hello
Farsi: [https://github.com/persepolisdm/persepolis/wiki/debian-installation-instruction-fa](url)
English: [https://github.com/persepolisdm/persepolis/wiki/debian-installation-instruction](url)

**Comment by iman-salmani** [comment]
Hello
Persepolis was also inside the Deepin Store.

**Comment by Pakrohk** [comment]
There are links to: notfund404
![deepinscreenshot_select-area_20180519215514](https://user-images.githubusercontent.com/27810360/40271212-68813f82-5baf-11e8-9e67-826d0b13f20d.png)

Old catalog version.

**Comment by mostafaasadi** [comment]
Hi
special thanks to @iman-salmani 
[https://github.com/persepolisdm/persepolis/wiki/debian-installation-instruction-fa](https://github.com/persepolisdm/persepolis/wiki/debian-installation-instruction-fa)
https://github.com/persepolisdm/persepolis/wiki/debian-installation-instruction
