### ISSUE TITLE
DistributionNotFound Error

### ISSUE THREAD

**Issue by LinArcX** [persepolisdm/persepolis#556]
**System Details:**
* Operating System: Gnu/Linux
* Distro(For GNU/Linux and BSD users): Arch
* Desktop Environment(For GNU/Linux and BSD users): Gnome
* Persepolis Version: ?
* How do you install Persepolis? Repositories

* _Please attach log files if crash or paste error message_

**Issue Description and steps to reproduce:**
Hi. until now, persepolis work greatly, but this day i want to open it, it did not respond. i open it from termianl and he says:
```
Traceback (most recent call last):
  File "/usr/bin/persepolis", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3095, in <module>
    @_call_aside
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3079, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3108, in _initialize_master_working_set                                                        
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 570, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 888, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 774, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'persepolis==3.1.0' distribution was not found and is required by the applicatio
```

**Comment by alireza-amirsamimi** [comment]
Hello
Please reinstall persepolis. It solves the problem :)
