### ISSUE TITLE
Persepolis Crash

### ISSUE THREAD

**Issue by ghost** [persepolisdm/persepolis#609]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/persepolis/scripts/persepolis.py", line 430, in main
    mainwindow = MainWindow(start_in_tray, persepolis_download_manager, persepolis_download_manager.setting)
  File "/usr/lib/python3/dist-packages/persepolis/scripts/mainwindow.py", line 929, in __init__
    dict = download_table_dict[gid]
KeyError: '38854fb43c260f6f'

**Comment by alireza-amirsamimi** [comment]
Hello
Can you explain more?
When did it happen?
What is your OS?
Which version of persepolis do you use?
