### ISSUE TITLE
VideoFinder button missing

### ISSUE THREAD

**Issue by ShakaZ75** [persepolisdm/persepolis#633]
![Persepolis - VideoFinder button missing](https://user-images.githubusercontent.com/50906955/58162619-d1440780-7c82-11e9-8905-8866043629b8.png)
**System Details:**
* Operating System: Linux
* Distro(For GNU/Linux and BSD users): Linux Mint  18.3
* Desktop Environment(For GNU/Linux and BSD users): KDE
* Persepolis Version: 3.0.1
* How do you install Persepolis? Repository from persepolis ppa

* _Please attach log files if crash or paste error message_

**Issue Description and steps to reproduce:**
#### Please report only one Issue (Bug or feature request or ...) in one issue! and open new Issue for another one :)
Hello, after 1st installation of Persepolis and FF integration addon, I have trouble with the following :
1° Missing Video Finder button in the Persepolis Download Manager interface (see attached screenshot)

Here's some basic info about my config :
Linux Mint KDE 18.3
Firefox 67
Persepolis 3.0.1
Persepolis download Manager Integration 2.0.0

**Comment by ShakaZ75** [comment]
After some more investigation it turns out this feature requires version 3.1.0 of Persepolis.
As the repository was on 3.0.1 I've tried installing from git. 
Persepolis now crashes on launch with below error msg : 

> /media/shakaz/Data/persepolis $ persepolis
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.5/dist-packages/persepolis-3.1.0-py3.5.egg/persepolis/scripts/mainwindow.py", line 50, in <module>
>   File "/usr/local/lib/python3.5/dist-packages/persepolis-3.1.0-py3.5.egg/persepolis/scripts/video_finder_addlink.py", line 26, in <module>
> ImportError: No module named 'youtube_dl'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/bin/persepolis", line 9, in <module>
>     load_entry_point('persepolis==3.1.0', 'console_scripts', 'persepolis')()
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
>     return get_distribution(dist).load_entry_point(group, name)
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
>     return ep.load()
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
>     return self.resolve()
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
>     module = __import__(self.module_name, fromlist=['__name__'], level=0)
>   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
>   File "/usr/local/lib/python3.5/dist-packages/persepolis-3.1.0-py3.5.egg/persepolis/__main__.py", line 20, in <module>
>   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
>   File "/usr/local/lib/python3.5/dist-packages/persepolis-3.1.0-py3.5.egg/persepolis/scripts/persepolis.py", line 88, in <module>
>   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
>   File "/usr/local/lib/python3.5/dist-packages/persepolis-3.1.0-py3.5.egg/persepolis/scripts/mainwindow.py", line 52, in <module>
> NameError: name 'ModuleNotFoundError' is not defined

Youtube-dl is installed though : 

> /media/shakaz/Data/persepolis $ youtube-dl --version
> 2019.05.20

**Comment by alireza-amirsamimi** [comment]
Hello
Mint 18.3 is based on ubuntu 16.04 and it is a little old :)
You must install youtube-dl with pip in ubuntu 16.04 and mint 18.3.
