### ISSUE TITLE
it doesn't work

### ISSUE THREAD

**Issue by SEMSOFT** [persepolisdm/persepolis#654]
**System Details:**
* Operating System: GNU/Linux
* Distro(For GNU/Linux and BSD users): Ubuntu 18.04.2 LTS x86_64
* Desktop Environment(For GNU/Linux and BSD users): GNOME 3.28.4
* Persepolis Version: 3.1.0.0
* How do you install Persepolis? Repositories
`
Traceback (most recent call last):
  File "/usr/bin/persepolis", line 11, in <module>
    load_entry_point('persepolis==3.1.0', 'console_scripts', 'persepolis')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/persepolis/__main__.py", line 20, in <module>
    from persepolis.scripts import persepolis
  File "/usr/lib/python3/dist-packages/persepolis/scripts/persepolis.py", line 88, in <module>
    from persepolis.scripts.mainwindow import MainWindow
  File "/usr/lib/python3/dist-packages/persepolis/scripts/mainwindow.py", line 62, in <module>
    from persepolis.scripts.video_finder_addlink import VideoFinderAddLink
  File "/usr/lib/python3/dist-packages/persepolis/scripts/video_finder_addlink.py", line 26, in <module>
    import youtube_dl
ModuleNotFoundError: No module named 'youtube_dl'
`

**Comment by alireza-amirsamimi** [comment]
@SEMSOFT Hello
Persepolis can't find youtube-dl module on your system.
Please install youtube-dl package from official repositories. 
If problem doesn't solve, then install youtube-dl with pip. 
Visit this link for more help:
https://ytdl-org.github.io/youtube-dl/download.html
