### ISSUE TITLE
database or disk is full

### ISSUE THREAD

**Issue by ArmanEsf** [persepolisdm/persepolis#655]
**System Details:**
* Operating System: GNU/LINUX
* Distro(For GNU/Linux and BSD users): Ubuntu 18.04 LTS
* Desktop Environment(For GNU/Linux and BSD users): XFCE4
* Persepolis Version: no idea right now :/
* How do you install Persepolis? (Repositories, source, ...): Repositories

* _Please attach log files if crash or paste error message_

**Issue Description and steps to reprodudffce:**
#### Please report only one Issue (Bug or feature request or ...) in one issue! and open new Issue for another one :)

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/persepolis-3.1.0-py3.6.egg/persepolis/scripts/persepolis.py", line 430, in main
    mainwindow = MainWindow(start_in_tray, persepolis_download_manager, persepolis_download_manager.setting)
  File "/usr/local/lib/python3.6/dist-packages/persepolis-3.1.0-py3.6.egg/persepolis/scripts/mainwindow.py", line 909, in __init__
    self.persepolis_db.setDBTablesToDefaultValue()
  File "/usr/local/lib/python3.6/dist-packages/persepolis-3.1.0-py3.6.egg/persepolis/scripts/data_base.py", line 1098, in setDBTablesToDefaultValue
    reverse = 'no', limit_enable = 'no', after_download = 'no'""")
sqlite3.OperationalError: database or disk is full

**Comment by alireza-amirsamimi** [comment]
@ArmanEsf Hi
Do you have enough free space in your /home ?
