### ISSUE TITLE
Persepolis crashed after i changed my linux login name

### ISSUE THREAD

**Issue by engrrasaq** [persepolisdm/persepolis#706]
**System Details:**hp elite book 8470P
* Operating System: linux
* Distro(For GNU/Linux and BSD users): ?mx-linux
* Desktop Environment(For GNU/Linux and BSD users): ?xfce
* Persepolis Version: ?3.1 also 3.2
* How do you install Persepolis? (Repositories, source, ...)using .deb file from github

* _Please attach log files if crash or paste error message_
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/persepolis/scripts/persepolis.py", line 433, in main
    mainwindow = MainWindow(start_in_tray, persepolis_download_manager, persepolis_download_manager.setting)
  File "/usr/lib/python3/dist-packages/persepolis/scripts/mainwindow.py", line 1306, in __init__
    self.persepolis_db.setDBTablesToDefaultValue()
  File "/usr/lib/python3/dist-packages/persepolis/scripts/data_base.py", line 1145, in setDBTablesToDefaultValue
    WHERE status NOT IN ('complete', 'error')""")
sqlite3.DatabaseError: database disk image is malformed

**Issue Description and steps to reproduce:**
#### Please report only one Issue (Bug or feature request or ...) in one issue! and open new Issue for another one :)

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/persepolis/scripts/persepolis.py", line 433, in main
    mainwindow = MainWindow(start_in_tray, persepolis_download_manager, persepolis_download_manager.setting)
  File "/usr/lib/python3/dist-packages/persepolis/scripts/mainwindow.py", line 1306, in __init__
    self.persepolis_db.setDBTablesToDefaultValue()
  File "/usr/lib/python3/dist-packages/persepolis/scripts/data_base.py", line 1145, in setDBTablesToDefaultValue
    WHERE status NOT IN ('complete', 'error')""")
sqlite3.DatabaseError: database disk image is malformed

**Comment by alireza-amirsamimi** [comment]
@engrrasaq Hello
Your database file is corrupted. Perhaps your hard disk have some issues or ... . Run this command from terminal for fixing this error.


`persepolis --clear`
