### ISSUE TITLE
Wrong python environment path

### ISSUE THREAD

**Issue by 0mids** [persepolisdm/persepolis#712]
**System Details:**
* Operating System: Gnu/Linu
* Distro(For GNU/Linux and BSD users): Arch
* Desktop Environment(For GNU/Linux and BSD users): Plasma
* Persepolis Version: 3.2.0
* How do you install Persepolis? AUR

> 
> Traceback (most recent call last):
>   File "/usr/bin/persepolis", line 6, in <module>
>     from pkg_resources import load_entry_point
>   File "/home/omid/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3241, in <module>
>     @_call_aside
>   File "/home/omid/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3225, in _call_aside
>     f(*args, **kwargs)
>   File "/home/omid/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3254, in _initialize_master_working_set
>     working_set = WorkingSet._build_master()
>   File "/home/omid/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
>     ws.require(__requires__)
>   File "/home/omid/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
>     needed = self.resolve(parse_requirements(requirements))
>   File "/home/omid/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
>     raise DistributionNotFound(req, requirers)
> **pkg_resources.DistributionNotFound: The 'persepolis==3.2.0' distribution was not found and is required by the application**

From the log, python can't assert that Persepolis exists! So I took a look at executable at /usr/bin/persepolis and it revealed python path was set to that of my anaconda installation (#!/home/omid/anaconda3/bin/python3.7). 

Finally changing it to /usr/bin/python3.7 solved the problem and Persepolis Started Successfully.

**Comment by alireza-amirsamimi** [comment]
Hello
Persepolis uses python setup tools for installation. Python-setup-tools creates that file in bin folder automatically. Do you change anything in your python settings or ...?

**Comment by crimx** [comment]
I suffer the same issue after a system upgrade on Manjaro. Don't know what went wrong.

```
Traceback (most recent call last):
  File "/usr/bin/persepolis", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3252, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'persepolis==3.2.0' distribution was not found and is required by the application
```

This is my `/usr/bin/persepolis`

```python
#!/usr/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'persepolis==3.2.0','console_scripts','persepolis'
__requires__ = 'persepolis==3.2.0'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('persepolis==3.2.0', 'console_scripts', 'persepolis')()
    )

```

**Comment by ghost** [comment]
@crimx It seems that Manjaro recently switched to Python 3.8 and you must rebuild persepolis package to make it work with new python version. It's not related to persepolis but all python packages must rebuild again after every new python version come along.
just rebuild it, and it would be fine again.

**Comment by crimx** [comment]
Thanks! Confirm worked after a fresh reinstall.

**Comment by ghost** [comment]
@crimx You're welcome
