### ISSUE TITLE
Bug: downloading from youtube.

### ISSUE THREAD

**Issue by mrostd** [persepolisdm/persepolis#713]
**System Details:**
* Operating System: Gnu/Linux
* Distro(For GNU/Linux and BSD users): Opensuse Tumbleweed
* Desktop Environment(For GNU/Linux and BSD users): Gnome 3.32.2
* Persepolis Version: 3.2.0
* How do you install Persepolis? (Repositories, source, ...) : Repositories

**Hello
Persepolis cannot complete my downloads from YouTube.
No problem with the internet.
There is no error message in Persepolis.**

Log File:
`2019-10-05 21:15:58,418 - Persepolis - INFO - chrome: Json file is created successfully.

persepolis executer file is created successfully.
2019-10-05 21:15:58,429 - Persepolis - INFO - chromium: Json file is created successfully.
persepolis executer file is created successfully.
2019-10-05 21:15:58,440 - Persepolis - INFO - opera: Json file is created successfully.
persepolis executer file is created successfully.
2019-10-05 21:15:58,450 - Persepolis - INFO - vivaldi: Json file is created successfully.
persepolis executer file is created successfully.
2019-10-05 21:15:58,461 - Persepolis - INFO - firefox: Json file is created successfully.
persepolis executer file is created successfully.
2019-10-05 21:15:59,652 - Persepolis - INFO - youtube_dl version: 2019.09.28
2019-10-05 21:16:00,177 - Persepolis - INFO - Aria2 is running
2019-10-05 21:16:00,177 - Persepolis - INFO - Aria2 version: 1.34.0
2019-10-05 21:16:00,179 - Persepolis - INFO - 
**********
ffmpeg version 4.2.1 Copyright (c) 2000-2019 the FFmpeg developers
built with gcc 9 (SUSE Linux) configuration: --prefix=/usr
--libdir=/usr/lib64 --shlibdir=/usr/lib64 --incdir=/usr/include/ffmpeg
--extra-cflags='-O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong
-funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection
-Werror=return-type -flto=1 -g' --optflags='-O2 -Wall
-D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables
-fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-
type -flto=1 -g' --disable-htmlpages --enable-pic --disable-stripping
--enable-shared --disable-static --enable-gpl --disable-openssl
--enable-avresample --enable-gnutls --enable-ladspa --enable-libaom
--enable-libass --enable-libbluray --enable-libbs2b --enable-libcelt
--enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-
libdc1394 --enable-libdrm --enable-libfontconfig --enable-libfreetype
--enable-libfribidi --enable-libgsm --enable-libjack --enable-
libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt
--enable-libopus --enable-libpulse --enable-librubberband --enable-
libsoxr --enable-libspeex --enable-libssh --enable-libsrt --enable-
libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis
--enable-libv4l2 --enable-libvpx --enable-libwebp --enable-libxml2
--enable-libzimg --enable-libzmq --enable-libzvbi --enable-lto
--enable-lv2 --enable-libmfx --enable-vaapi --enable-vdpau --enable-
libfdk-aac-dlopen --enable-nonfree --enable-libvo-amrwbenc --enable-
version3 --enable-libx264 --enable-libx265 --enable-librtmp --enable-
libxvid libavutil      56. 31.100 / 56. 31.100 libavcodec     58.
54.100 / 58. 54.100 libavformat    58. 29.100 / 58. 29.100 libavdevice
58.  8.100 / 58.  8.100 libavfilter     7. 57.100 /  7. 57.100

libavresample   4.  0.  0 /  4.  0.  0 libswscale      5.  5.100 /  5.

5.100 libswresample   3.  5.100 /  3.  5.100 libpostproc    55.  5.100

/ 55.  5.100

**********

2019-10-05 21:16:00,179 - Persepolis - INFO - python version: 3.7.3 (default, Apr 09 2019, 05:18:21) [GCC]

2019-10-05 21:16:00,179 - Persepolis - INFO - QT version: 5.13.1

2019-10-05 21:16:00,179 - Persepolis - INFO - PyQt version: 5.13.1

2019-10-05 21:16:00,179 - Persepolis - INFO - Operating system: Linux

2019-10-05 21:16:00,180 - Persepolis - INFO - Desktop env.: GNOME

2019-10-05 21:16:11,837 - Persepolis - ERROR - Download did not start

2019-10-05 21:16:11,839 - Persepolis - ERROR - Traceback (most recent call last):

  File "/usr/lib/python3.7/site-packages/persepolis/scripts/download.py", line 284, in downloadAria

    answer = server.aria2.addUri([link], aria_dict)

  File "/usr/lib64/python3.7/xmlrpc/client.py", line 1112, in __call__

    return self.__send(self.__name, args)

  File "/usr/lib64/python3.7/xmlrpc/client.py", line 1452, in __request

    verbose=self.__verbose

  File "/usr/lib64/python3.7/xmlrpc/client.py", line 1154, in request

    return self.single_request(host, handler, request_body, verbose)

  File "/usr/lib64/python3.7/xmlrpc/client.py", line 1167, in single_request

    resp = http_conn.getresponse()

  File "/usr/lib64/python3.7/http/client.py", line 1323, in getresponse

    raise ResponseNotReady(self.__state)

http.client.ResponseNotReady: Idle

2019-10-05 21:16:12,876 - Persepolis - INFO - 7d72e9db11d5ed9b paused

2019-10-05 21:18:52,062 - Persepolis - INFO - 7d72e9db11d5ed9b unpaused

2019-10-05 21:18:53,674 - Persepolis - ERROR - Download failed - GID : 7d72e9db11d5ed9b- Message : The response status is not successful. status=403

Persepolis Download Manager, 2019/10/05 21:19:01

2019-10-05 21:19:01,660 - Persepolis - INFO - chrome: Json file is created successfully.

persepolis executer file is created successfully.

2019-10-05 21:19:01,672 - Persepolis - INFO - chromium: Json file is created successfully.

persepolis executer file is created successfully.

2019-10-05 21:19:01,682 - Persepolis - INFO - opera: Json file is created successfully.

persepolis executer file is created successfully.

2019-10-05 21:19:01,693 - Persepolis - INFO - vivaldi: Json file is created successfully.

persepolis executer file is created successfully.

2019-10-05 21:19:01,706 - Persepolis - INFO - firefox: Json file is created successfully.

persepolis executer file is created successfully.

2019-10-05 21:19:02,656 - Persepolis - INFO - youtube_dl version: 2019.09.28

2019-10-05 21:19:03,008 - Persepolis - INFO - Aria2 is running

2019-10-05 21:19:03,013 - Persepolis - INFO - Aria2 version: 1.34.0

2019-10-05 21:19:03,131 - Persepolis - INFO - 

**********

ffmpeg version 4.2.1 Copyright (c) 2000-2019 the FFmpeg developers

built with gcc 9 (SUSE Linux) configuration: --prefix=/usr

--libdir=/usr/lib64 --shlibdir=/usr/lib64 --incdir=/usr/include/ffmpeg

--extra-cflags='-O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong

-funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection

-Werror=return-type -flto=1 -g' --optflags='-O2 -Wall

-D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables

-fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-

type -flto=1 -g' --disable-htmlpages --enable-pic --disable-stripping

--enable-shared --disable-static --enable-gpl --disable-openssl

--enable-avresample --enable-gnutls --enable-ladspa --enable-libaom

--enable-libass --enable-libbluray --enable-libbs2b --enable-libcelt

--enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-

libdc1394 --enable-libdrm --enable-libfontconfig --enable-libfreetype

--enable-libfribidi --enable-libgsm --enable-libjack --enable-

libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt

--enable-libopus --enable-libpulse --enable-librubberband --enable-

libsoxr --enable-libspeex --enable-libssh --enable-libsrt --enable-

libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis

--enable-libv4l2 --enable-libvpx --enable-libwebp --enable-libxml2

--enable-libzimg --enable-libzmq --enable-libzvbi --enable-lto

--enable-lv2 --enable-libmfx --enable-vaapi --enable-vdpau --enable-

libfdk-aac-dlopen --enable-nonfree --enable-libvo-amrwbenc --enable-

version3 --enable-libx264 --enable-libx265 --enable-librtmp --enable-

libxvid libavutil      56. 31.100 / 56. 31.100 libavcodec     58.

54.100 / 58. 54.100 libavformat    58. 29.100 / 58. 29.100 libavdevice

58.  8.100 / 58.  8.100 libavfilter     7. 57.100 /  7. 57.100

libavresample   4.  0.  0 /  4.  0.  0 libswscale      5.  5.100 /  5.

5.100 libswresample   3.  5.100 /  3.  5.100 libpostproc    55.  5.100

/ 55.  5.100

**********

2019-10-05 21:19:03,131 - Persepolis - INFO - python version: 3.7.3 (default, Apr 09 2019, 05:18:21) [GCC]

2019-10-05 21:19:03,131 - Persepolis - INFO - QT version: 5.13.1

2019-10-05 21:19:03,131 - Persepolis - INFO - PyQt version: 5.13.1

2019-10-05 21:19:03,131 - Persepolis - INFO - Operating system: Linux

2019-10-05 21:19:03,132 - Persepolis - INFO - Desktop env.: GNOME

2019-10-05 21:21:54,930 - Persepolis - ERROR - Spider couldn't find file name

2019-10-05 21:21:54,930 - Persepolis - ERROR - Spider couldn't find file size

2019-10-05 21:37:04,244 - Persepolis - ERROR - Spider couldn't find file name

2019-10-05 21:37:04,245 - Persepolis - ERROR - Spider couldn't find file size

===================================================

Persepolis Download Manager, 2019/10/06 09:33:02

2019-10-06 09:33:02,957 - Persepolis - INFO - chrome: Json file is created successfully.

persepolis executer file is created successfully.

2019-10-06 09:33:02,970 - Persepolis - INFO - chromium: Json file is created successfully.

persepolis executer file is created successfully.

2019-10-06 09:33:03,093 - Persepolis - INFO - opera: Json file is created successfully.

persepolis executer file is created successfully.

2019-10-06 09:33:03,252 - Persepolis - INFO - vivaldi: Json file is created successfully.

persepolis executer file is created successfully.

2019-10-06 09:33:03,267 - Persepolis - INFO - firefox: Json file is created successfully.

persepolis executer file is created successfully.

2019-10-06 09:33:10,652 - Persepolis - INFO - youtube_dl version: 2019.09.28

2019-10-06 09:33:11,976 - Persepolis - ERROR - Aria2 didn't respond!

2019-10-06 09:33:11,978 - Persepolis - INFO - Starting Aria2

2019-10-06 09:33:13,999 - Persepolis - INFO - Aria2 is running

2019-10-06 09:33:13,999 - Persepolis - INFO - Aria2 version: 1.34.0

2019-10-06 09:33:14,364 - Persepolis - INFO - 

**********

ffmpeg version 4.2.1 Copyright (c) 2000-2019 the FFmpeg developers

built with gcc 9 (SUSE Linux) configuration: --prefix=/usr

--libdir=/usr/lib64 --shlibdir=/usr/lib64 --incdir=/usr/include/ffmpeg

--extra-cflags='-O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong

-funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection

-Werror=return-type -flto=1 -g' --optflags='-O2 -Wall

-D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables

-fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-

type -flto=1 -g' --disable-htmlpages --enable-pic --disable-stripping

--enable-shared --disable-static --enable-gpl --disable-openssl

--enable-avresample --enable-gnutls --enable-ladspa --enable-libaom

--enable-libass --enable-libbluray --enable-libbs2b --enable-libcelt

--enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-

libdc1394 --enable-libdrm --enable-libfontconfig --enable-libfreetype

--enable-libfribidi --enable-libgsm --enable-libjack --enable-

libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt

--enable-libopus --enable-libpulse --enable-librubberband --enable-

libsoxr --enable-libspeex --enable-libssh --enable-libsrt --enable-

libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis

--enable-libv4l2 --enable-libvpx --enable-libwebp --enable-libxml2

--enable-libzimg --enable-libzmq --enable-libzvbi --enable-lto

--enable-lv2 --enable-libmfx --enable-vaapi --enable-vdpau --enable-

libfdk-aac-dlopen --enable-nonfree --enable-libvo-amrwbenc --enable-

version3 --enable-libx264 --enable-libx265 --enable-librtmp --enable-

libxvid libavutil      56. 31.100 / 56. 31.100 libavcodec     58.

54.100 / 58. 54.100 libavformat    58. 29.100 / 58. 29.100 libavdevice

58.  8.100 / 58.  8.100 libavfilter     7. 57.100 /  7. 57.100

libavresample   4.  0.  0 /  4.  0.  0 libswscale      5.  5.100 /  5.

5.100 libswresample   3.  5.100 /  3.  5.100 libpostproc    55.  5.100

/ 55.  5.100

**********

2019-10-06 09:33:14,365 - Persepolis - INFO - python version: 3.7.3 (default, Apr 09 2019, 05:18:21) [GCC]

2019-10-06 09:33:14,365 - Persepolis - INFO - QT version: 5.13.1

2019-10-06 09:33:14,365 - Persepolis - INFO - PyQt version: 5.13.1

2019-10-06 09:33:14,365 - Persepolis - INFO - Operating system: Linux

2019-10-06 09:33:14,365 - Persepolis - INFO - Desktop env.: GNOME

2019-10-06 09:54:43,413 - Persepolis - INFO - f3475fc5a8b54f17 Starts

Persepolis Download Manager, 2019/10/06 09:54:47

2019-10-06 09:54:47,335 - Persepolis - INFO - chrome: Json file is created successfully.

persepolis executer file is created successfully.

2019-10-06 09:54:47,348 - Persepolis - INFO - chromium: Json file is created successfully.

persepolis executer file is created successfully.

2019-10-06 09:54:47,359 - Persepolis - INFO - opera: Json file is created successfully.

persepolis executer file is created successfully.

2019-10-06 09:54:47,372 - Persepolis - INFO - vivaldi: Json file is created successfully.

persepolis executer file is created successfully.

2019-10-06 09:54:47,384 - Persepolis - INFO - firefox: Json file is created successfully.

persepolis executer file is created successfully.

2019-10-06 09:54:48,400 - Persepolis - INFO - youtube_dl version: 2019.09.28

2019-10-06 09:54:48,726 - Persepolis - INFO - Aria2 is running

2019-10-06 09:54:48,726 - Persepolis - INFO - Aria2 version: 1.34.0

2019-10-06 09:54:48,955 - Persepolis - INFO - 

**********

ffmpeg version 4.2.1 Copyright (c) 2000-2019 the FFmpeg developers

built with gcc 9 (SUSE Linux) configuration: --prefix=/usr

--libdir=/usr/lib64 --shlibdir=/usr/lib64 --incdir=/usr/include/ffmpeg

--extra-cflags='-O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong

-funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection

-Werror=return-type -flto=1 -g' --optflags='-O2 -Wall

-D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables

-fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-

type -flto=1 -g' --disable-htmlpages --enable-pic --disable-stripping

--enable-shared --disable-static --enable-gpl --disable-openssl

--enable-avresample --enable-gnutls --enable-ladspa --enable-libaom

--enable-libass --enable-libbluray --enable-libbs2b --enable-libcelt

--enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-

libdc1394 --enable-libdrm --enable-libfontconfig --enable-libfreetype

--enable-libfribidi --enable-libgsm --enable-libjack --enable-

libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt

--enable-libopus --enable-libpulse --enable-librubberband --enable-

libsoxr --enable-libspeex --enable-libssh --enable-libsrt --enable-

libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis

--enable-libv4l2 --enable-libvpx --enable-libwebp --enable-libxml2

--enable-libzimg --enable-libzmq --enable-libzvbi --enable-lto

--enable-lv2 --enable-libmfx --enable-vaapi --enable-vdpau --enable-

libfdk-aac-dlopen --enable-nonfree --enable-libvo-amrwbenc --enable-

version3 --enable-libx264 --enable-libx265 --enable-librtmp --enable-

libxvid libavutil      56. 31.100 / 56. 31.100 libavcodec     58.

54.100 / 58. 54.100 libavformat    58. 29.100 / 58. 29.100 libavdevice

58.  8.100 / 58.  8.100 libavfilter     7. 57.100 /  7. 57.100

libavresample   4.  0.  0 /  4.  0.  0 libswscale      5.  5.100 /  5.

5.100 libswresample   3.  5.100 /  3.  5.100 libpostproc    55.  5.100

/ 55.  5.100

**********

2019-10-06 09:54:48,956 - Persepolis - INFO - python version: 3.7.3 (default, Apr 09 2019, 05:18:21) [GCC]

2019-10-06 09:54:48,956 - Persepolis - INFO - QT version: 5.13.1

2019-10-06 09:54:48,956 - Persepolis - INFO - PyQt version: 5.13.1

2019-10-06 09:54:48,956 - Persepolis - INFO - Operating system: Linux

2019-10-06 09:54:48,956 - Persepolis - INFO - Desktop env.: GNOME

`
![Screenshot from 2019-10-06 10-06-33](https://user-images.githubusercontent.com/53259265/66265587-f72f0a80-e825-11e9-9c7c-1fbbc230bc94.png)

**Comment by alireza-amirsamimi** [comment]
Hello
Can you explain more? Or can you attach a video from your download progress?
Is video finder able to find your video?
