### ISSUE TITLE
Video file Crash problem

### ISSUE THREAD

**Issue by Pakrohk** [persepolisdm/persepolis#714]
**System Details:**
* Operating System: Gnu/Linux
* Distro(For GNU/Linux and BSD users): Arch
* Desktop Environment(For GNU/Linux and BSD users): kde
* Persepolis Version: Aur

When I download a file from https://www.desktophut.com/ with the help of Perspolis, the file crashes, there is no problem in normal mode.

**Comment by alireza-amirsamimi** [comment]
Hello
Please run Persepolis from terminal and tell me the error message.

**Comment by Pakrohk** [comment]
> Hello
> Please run Persepolis from terminal and tell me the error message.

Persepolis in Terminal 
```
➜  ~ persepolis             
Icon theme "elementary" not found.
Icon theme "gnome" not found.

```

Persepolis Log File:
```
5.100 libswresample   3.  5.100 /  3.  5.100 libpostproc    55.  5.100

/ 55.  5.100

**********



2019-10-04 15:57:23,076 - Persepolis - INFO - python version: 3.7.4 (default, Jul 16 2019, 07:12:58) 

[GCC 9.1.0]

2019-10-04 15:57:23,076 - Persepolis - INFO - QT version: 5.13.1

2019-10-04 15:57:23,076 - Persepolis - INFO - PyQt version: 5.13.1

2019-10-04 15:57:23,076 - Persepolis - INFO - Operating system: Linux

2019-10-04 15:57:23,076 - Persepolis - INFO - Desktop env.: KDE

2019-10-04 15:57:24,603 - Persepolis - INFO - Aria2 is running

2019-10-04 15:57:24,603 - Persepolis - INFO - Aria2 version: 1.34.0

2019-10-04 19:18:28,990 - Persepolis - INFO - 8febc72d5ad700d6 Starts

2019-10-04 19:18:32,873 - Persepolis - INFO - Download speed limit  value is changed

2019-10-04 19:21:37,605 - Persepolis - ERROR - Spider couldn't find file name

2019-10-04 19:56:14,458 - Persepolis - INFO - Download complete - GID : 8febc72d5ad700d6

2019-10-04 19:56:15,147 - Persepolis - INFO - e06aedd7ad3209e0 Starts

2019-10-04 20:33:01,888 - Persepolis - INFO - Download complete - GID : e06aedd7ad3209e0

2019-10-04 20:33:01,989 - Persepolis - INFO - f20eec5f045daafa Starts

2019-10-04 21:39:11,223 - Persepolis - INFO - Download complete - GID : f20eec5f045daafa

2019-10-04 21:39:11,337 - Persepolis - INFO - f1fe4aae8cdf0673 Starts

2019-10-04 21:49:09,254 - Persepolis - INFO - Download complete - GID : f1fe4aae8cdf0673

2019-10-04 21:49:10,262 - Persepolis - INFO - Queue completed

2019-10-05 11:42:35,922 - Persepolis - INFO - beeec23fae867da1 Starts

2019-10-05 11:42:39,787 - Persepolis - INFO - Download speed limit  value is changed

2019-10-05 12:11:08,584 - Persepolis - INFO - Download complete - GID : beeec23fae867da1

2019-10-05 12:11:08,670 - Persepolis - INFO - 8bf17a7816bdcf0e Starts

2019-10-05 12:39:44,215 - Persepolis - INFO - Download complete - GID : 8bf17a7816bdcf0e

2019-10-05 12:39:44,302 - Persepolis - INFO - 2c8a44ae7578d65a Starts

2019-10-05 12:50:45,578 - Persepolis - INFO - Download complete - GID : 2c8a44ae7578d65a

2019-10-05 12:50:45,714 - Persepolis - INFO - Queue completed

2019-10-05 15:44:33,740 - Persepolis - ERROR - Spider couldn't find file name

2019-10-05 15:44:33,755 - Persepolis - ERROR - Spider couldn't find file size

2019-10-05 15:45:02,051 - Persepolis - INFO - 17350b3248808c16 Starts

2019-10-05 15:58:34,361 - Persepolis - INFO - Download complete - GID : 17350b3248808c16

2019-10-05 18:11:37,231 - Persepolis - ERROR - Spider couldn't find file name

2019-10-05 18:11:37,232 - Persepolis - ERROR - Spider couldn't find file size

2019-10-05 18:11:40,539 - Persepolis - INFO - 6cb31438571efc07 Starts

2019-10-05 18:18:29,488 - Persepolis - INFO - Download complete - GID : 6cb31438571efc07

2019-10-05 18:23:01,815 - Persepolis - ERROR - Spider couldn't find file name

2019-10-05 18:23:04,788 - Persepolis - INFO - 685478f38a7e5188 Starts

2019-10-05 18:26:18,892 - Persepolis - INFO - Download complete - GID : 685478f38a7e5188

2019-10-06 12:54:01,777 - Persepolis - ERROR - Spider couldn't find file name

2019-10-06 12:54:01,816 - Persepolis - ERROR - Spider couldn't find file size

2019-10-06 12:54:25,360 - Persepolis - INFO - 2e8c26250e7bd265 Starts

2019-10-06 12:54:47,406 - Persepolis - INFO - Download complete - GID : 2e8c26250e7bd265

2019-10-06 13:42:23,055 - Persepolis - ERROR - Aria2 didn't respond!

2019-10-06 13:42:23,241 - Persepolis - ERROR - Download did not start

2019-10-06 13:42:23,409 - Persepolis - ERROR - Traceback (most recent call last):

  File "/usr/lib/python3.7/site-packages/persepolis/scripts/download.py", line 284, in downloadAria

    answer = server.aria2.addUri([link], aria_dict)

  File "/usr/lib/python3.7/xmlrpc/client.py", line 1112, in __call__

    return self.__send(self.__name, args)

  File "/usr/lib/python3.7/xmlrpc/client.py", line 1452, in __request

    verbose=self.__verbose

  File "/usr/lib/python3.7/xmlrpc/client.py", line 1154, in request

    return self.single_request(host, handler, request_body, verbose)

  File "/usr/lib/python3.7/xmlrpc/client.py", line 1167, in single_request

    resp = http_conn.getresponse()

  File "/usr/lib/python3.7/http/client.py", line 1326, in getresponse

    raise ResponseNotReady(self.__state)

http.client.ResponseNotReady: Idle



2019-10-06 13:42:25,118 - Persepolis - INFO - Reconnecting Aria2 ...

2019-10-06 13:42:25,119 - Persepolis - INFO - Persepolis reconnected aria2 successfully

2019-10-06 13:42:25,415 - Persepolis - ERROR - Download failed - GID : 94014eb976aa1a47- Message : Error

2019-10-06 13:42:26,266 - Persepolis - ERROR - Spider couldn't find file name

2019-10-06 13:42:54,289 - Persepolis - INFO - b0c065328b6658de Starts

2019-10-06 13:42:55,930 - Persepolis - ERROR - Spider couldn't find file name

2019-10-06 13:43:16,256 - Persepolis - INFO - Download complete - GID : b0c065328b6658de

2019-10-06 13:44:25,407 - Persepolis - INFO - 992cd6660fda6800 Starts

2019-10-06 13:44:29,701 - Persepolis - ERROR - Spider couldn't find file size

2019-10-06 13:44:40,086 - Persepolis - INFO - 992cd6660fda6800 stopped

2019-10-06 13:44:40,248 - Persepolis - INFO - Download stoped - GID : 992cd6660fda6800

2019-10-06 13:46:07,826 - Persepolis - INFO - 8959e52e0a197ed4 Starts

2019-10-06 13:46:08,215 - Persepolis - ERROR - Spider couldn't find file name

2019-10-06 13:46:53,837 - Persepolis - INFO - 8959e52e0a197ed4 paused

2019-10-06 13:46:55,998 - Persepolis - INFO - 8959e52e0a197ed4 stopped

2019-10-06 13:46:56,582 - Persepolis - INFO - Download stoped - GID : 8959e52e0a197ed4

2019-10-06 13:51:19,000 - Persepolis - INFO - Please wait ...

2019-10-06 13:51:19,005 - Persepolis - INFO - Aria2 Shutdown : OK

2019-10-06 13:51:19,708 - Persepolis - INFO - Persepolis closed!

Persepolis Download Manager, 2019/10/06 14:15:10

2019-10-06 14:15:10,959 - Persepolis - INFO - chrome: Json file is created successfully.

persepolis executer file is created successfully.



2019-10-06 14:15:10,977 - Persepolis - INFO - chromium: Json file is created successfully.

persepolis executer file is created successfully.



2019-10-06 14:15:10,996 - Persepolis - INFO - opera: Json file is created successfully.

persepolis executer file is created successfully.



2019-10-06 14:15:11,012 - Persepolis - INFO - vivaldi: Json file is created successfully.

persepolis executer file is created successfully.



2019-10-06 14:15:11,027 - Persepolis - INFO - firefox: Json file is created successfully.

persepolis executer file is created successfully.



2019-10-06 14:15:17,879 - Persepolis - INFO - youtube_dl version: 2019.09.28

2019-10-06 14:15:18,617 - Persepolis - ERROR - Aria2 didn't respond!

2019-10-06 14:15:18,617 - Persepolis - INFO - Starting Aria2

2019-10-06 14:15:18,942 - Persepolis - INFO - 

**********

ffmpeg version n4.2.1 Copyright (c) 2000-2019 the FFmpeg developers

built with gcc 9.1.0 (GCC) configuration: --prefix=/usr --disable-

debug --disable-static --disable-stripping --enable-fontconfig

--enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-

libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-

libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm

--enable-libiec61883 --enable-libjack --enable-libmodplug --enable-

libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb

--enable-libopenjpeg --enable-libopus --enable-libpulse --enable-

libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-

libv4l2 --enable-libvidstab --enable-libvorbis --enable-libvpx

--enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb

--enable-libxml2 --enable-libxvid --enable-nvdec --enable-nvenc

--enable-omx --enable-shared --enable-version3 libavutil      56.

31.100 / 56. 31.100 libavcodec     58. 54.100 / 58. 54.100 libavformat

58. 29.100 / 58. 29.100 libavdevice    58.  8.100 / 58.  8.100

libavfilter     7. 57.100 /  7. 57.100 libswscale      5.  5.100 /  5.

5.100 libswresample   3.  5.100 /  3.  5.100 libpostproc    55.  5.100

/ 55.  5.100

**********



2019-10-06 14:15:18,943 - Persepolis - INFO - python version: 3.7.4 (default, Jul 16 2019, 07:12:58) 

[GCC 9.1.0]

2019-10-06 14:15:18,943 - Persepolis - INFO - QT version: 5.13.1

2019-10-06 14:15:18,943 - Persepolis - INFO - PyQt version: 5.13.1

2019-10-06 14:15:18,943 - Persepolis - INFO - Operating system: Linux

2019-10-06 14:15:18,943 - Persepolis - INFO - Desktop env.: KDE

2019-10-06 14:15:20,633 - Persepolis - INFO - Aria2 is running

2019-10-06 14:15:20,634 - Persepolis - INFO - Aria2 version: 1.34.0

2019-10-06 14:15:39,582 - Persepolis - INFO - d2a948473e22cb9c Starts

2019-10-06 14:21:49,553 - Persepolis - INFO - Download complete - GID : d2a948473e22cb9c

2019-10-06 14:26:01,111 - Persepolis - INFO - 4ab865409a2e02ec Starts

2019-10-06 14:31:17,826 - Persepolis - INFO - Download complete - GID : 4ab865409a2e02ec

2019-10-06 15:13:50,833 - Persepolis - INFO - 849ce61c5e805d24 Starts

2019-10-06 15:14:39,035 - Persepolis - INFO - f2bddfe7ff8ea10a Starts

2019-10-06 15:14:39,038 - Persepolis - ERROR - Aria2 didn't respond!

2019-10-06 15:15:50,069 - Persepolis - INFO - Download complete - GID : 849ce61c5e805d24

2019-10-06 15:17:29,821 - Persepolis - INFO - Download complete - GID : f2bddfe7ff8ea10a

2019-10-06 23:30:42,145 - Persepolis - ERROR - Spider couldn't find file name

2019-10-06 23:32:10,548 - Persepolis - INFO - b97fc334cd4455a0 Starts

2019-10-06 23:54:29,705 - Persepolis - INFO - Download complete - GID : b97fc334cd4455a0

2019-10-07 00:45:38,734 - Persepolis - INFO - Please wait ...

2019-10-07 00:45:38,741 - Persepolis - INFO - Aria2 Shutdown : OK

2019-10-07 00:45:39,343 - Persepolis - INFO - Persepolis closed!

===================================================

Persepolis Download Manager, 2019/10/07 00:45:47

2019-10-07 00:45:48,211 - Persepolis - INFO - chrome: Json file is created successfully.

persepolis executer file is created successfully.



2019-10-07 00:45:48,225 - Persepolis - INFO - chromium: Json file is created successfully.

persepolis executer file is created successfully.



2019-10-07 00:45:48,237 - Persepolis - INFO - opera: Json file is created successfully.

persepolis executer file is created successfully.



2019-10-07 00:45:48,251 - Persepolis - INFO - vivaldi: Json file is created successfully.

persepolis executer file is created successfully.



2019-10-07 00:45:48,266 - Persepolis - INFO - firefox: Json file is created successfully.

persepolis executer file is created successfully.



2019-10-07 00:45:54,636 - Persepolis - INFO - youtube_dl version: 2019.09.28

2019-10-07 00:45:55,218 - Persepolis - ERROR - Aria2 didn't respond!

2019-10-07 00:45:55,218 - Persepolis - INFO - Starting Aria2

2019-10-07 00:45:55,568 - Persepolis - INFO - 

**********

ffmpeg version n4.2.1 Copyright (c) 2000-2019 the FFmpeg developers

built with gcc 9.1.0 (GCC) configuration: --prefix=/usr --disable-

debug --disable-static --disable-stripping --enable-fontconfig

--enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-

libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-

libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm

--enable-libiec61883 --enable-libjack --enable-libmodplug --enable-

libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb

--enable-libopenjpeg --enable-libopus --enable-libpulse --enable-

libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-

libv4l2 --enable-libvidstab --enable-libvorbis --enable-libvpx

--enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb

--enable-libxml2 --enable-libxvid --enable-nvdec --enable-nvenc

--enable-omx --enable-shared --enable-version3 libavutil      56.

31.100 / 56. 31.100 libavcodec     58. 54.100 / 58. 54.100 libavformat

58. 29.100 / 58. 29.100 libavdevice    58.  8.100 / 58.  8.100

libavfilter     7. 57.100 /  7. 57.100 libswscale      5.  5.100 /  5.

5.100 libswresample   3.  5.100 /  3.  5.100 libpostproc    55.  5.100

/ 55.  5.100

**********



2019-10-07 00:45:55,568 - Persepolis - INFO - python version: 3.7.4 (default, Oct  4 2019, 06:57:26) 

[GCC 9.2.0]

2019-10-07 00:45:55,568 - Persepolis - INFO - QT version: 5.13.1

2019-10-07 00:45:55,568 - Persepolis - INFO - PyQt version: 5.13.1

2019-10-07 00:45:55,569 - Persepolis - INFO - Operating system: Linux

2019-10-07 00:45:55,569 - Persepolis - INFO - Desktop env.: KDE

2019-10-07 00:45:57,277 - Persepolis - INFO - Aria2 is running

2019-10-07 00:45:57,277 - Persepolis - INFO - Aria2 version: 1.34.0

2019-10-07 00:48:58,261 - Persepolis - INFO - 3591d3793c4b483c Starts

2019-10-07 00:50:30,618 - Persepolis - INFO - Download complete - GID : 3591d3793c4b483c

Persepolis Download Manager, 2019/10/07 00:51:54

2019-10-07 00:51:54,292 - Persepolis - INFO - chrome: Json file is created successfully.

persepolis executer file is created successfully.



2019-10-07 00:51:54,308 - Persepolis - INFO - chromium: Json file is created successfully.

persepolis executer file is created successfully.



2019-10-07 00:51:54,323 - Persepolis - INFO - opera: Json file is created successfully.

persepolis executer file is created successfully.



2019-10-07 00:51:54,338 - Persepolis - INFO - vivaldi: Json file is created successfully.

persepolis executer file is created successfully.



2019-10-07 00:51:54,355 - Persepolis - INFO - firefox: Json file is created successfully.

persepolis executer file is created successfully.



2019-10-07 00:51:55,053 - Persepolis - INFO - youtube_dl version: 2019.09.28

2019-10-07 00:51:55,521 - Persepolis - ERROR - Aria2 didn't respond!

2019-10-07 00:51:55,521 - Persepolis - INFO - Starting Aria2

2019-10-07 00:51:55,634 - Persepolis - INFO - 

**********

ffmpeg version n4.2.1 Copyright (c) 2000-2019 the FFmpeg developers

built with gcc 9.1.0 (GCC) configuration: --prefix=/usr --disable-

debug --disable-static --disable-stripping --enable-fontconfig

--enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-

libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-

libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm

--enable-libiec61883 --enable-libjack --enable-libmodplug --enable-

libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb

--enable-libopenjpeg --enable-libopus --enable-libpulse --enable-

libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-

libv4l2 --enable-libvidstab --enable-libvorbis --enable-libvpx

--enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb

--enable-libxml2 --enable-libxvid --enable-nvdec --enable-nvenc

--enable-omx --enable-shared --enable-version3 libavutil      56.

31.100 / 56. 31.100 libavcodec     58. 54.100 / 58. 54.100 libavformat

58. 29.100 / 58. 29.100 libavdevice    58.  8.100 / 58.  8.100

libavfilter     7. 57.100 /  7. 57.100 libswscale      5.  5.100 /  5.

5.100 libswresample   3.  5.100 /  3.  5.100 libpostproc    55.  5.100

/ 55.  5.100

**********



2019-10-07 00:51:55,634 - Persepolis - INFO - python version: 3.7.4 (default, Oct  4 2019, 06:57:26) 

[GCC 9.2.0]

2019-10-07 00:51:55,634 - Persepolis - INFO - QT version: 5.13.1

2019-10-07 00:51:55,635 - Persepolis - INFO - PyQt version: 5.13.1

2019-10-07 00:51:55,635 - Persepolis - INFO - Operating system: Linux

2019-10-07 00:51:55,635 - Persepolis - INFO - Desktop env.: KDE

2019-10-07 00:51:57,552 - Persepolis - INFO - Aria2 is running

2019-10-07 00:51:57,552 - Persepolis - INFO - Aria2 version: 1.34.0

2019-10-07 00:53:19,179 - Persepolis - INFO - 6b674ccc3aff43d2 Starts

2019-10-07 00:54:44,787 - Persepolis - INFO - Download complete - GID : 6b674ccc3aff43d2


```

**Comment by alireza-amirsamimi** [comment]
Hello
We have no crash message! 
Did Persepolis crashed(closed) when you clicked on fetch media button?

**Comment by Pakrohk** [comment]
> Hello
> We have no crash message!
> Did Persepolis crashed(closed) when you clicked on fetch media button?

No, and this is strange to me ، The file should not be corrupted.

**Comment by alireza-amirsamimi** [comment]
@APakrohk سلام
لطفا با زبان فارسی از اول و کامل قضیه را توضیح بدید. ممنونم

**Comment by Pakrohk** [comment]
وقتی از سایتی که بالا لینک کردم فایل های ویدیو دانلود می کنم ، فایل نهایی خراب ، ولی وقتی این کار رو با مرورگر انجام میدم ، فایل بدون مشکل دانلود میشه.
این در حالی هستش که پرسپولیس هیچ خطایی هم نمیده ، یعنی عملیات کامل هستش و این برای من عجیب که چرا فایل باید خراب بشه.

**Comment by alireza-amirsamimi** [comment]
آیا از ویدیو یاب برای دانلود ویدیو استفاده کردید؟
منظورم همون
video finder
هست

**Comment by Pakrohk** [comment]
نه توی سایت یک گذینه برای دانلود کنار صفحه پایین سمت راست هست.

**Comment by alireza-amirsamimi** [comment]
لطفا لینک یکی از صفحانی که فایل برای دانلود داره رو بگذارید

**Comment by Pakrohk** [comment]
https://www.desktophut.com/games-live-wallpapers/lonely-tower-skyrim-live-wallpaper/

**Comment by alireza-amirsamimi** [comment]
<div dir="rtl">
جناب پاکرخ لینک رو آزمایش کردم. مشکلی عجیبی هست! وقتی تعداد کانکشن ها رو میگذارم روی ۱ فایل سالم دانلود میشه و وقتی تعداد کانکشن ها روی حالت پیش فرض ۱۶ هست، آریا فایل رو خراب میکنه.
موقع اضافه کردن لینک از قسمت more options تعداد کانکشن ها رو روی ۱ بگذارید.

**Comment by Pakrohk** [comment]
> جناب پاکرخ لینک رو آزمایش کردم. مشکلی عجیبی هست! وقتی تعداد کانکشن ها رو میگذارم روی ۱ فایل سالم دانلود میشه و وقتی تعداد کانکشن ها روی حالت پیش فرض ۱۶ هست، آریا فایل رو خراب میکنه. موقع اضافه کردن لینک از قسمت more options تعداد کانکشن ها رو روی ۱ بگذارید.
پاک روح هستم.  :blush: :bowtie:
بله واقعا مشکل عجیبی هستش.
ممنون که پیگیری کردین.
