### ISSUE TITLE
Startup error on Ubuntu 16.04

### ISSUE THREAD

**Issue by Aury88** [persepolisdm/persepolis#766]
**System Details:**
* Operating System: GNU/Linux 
* Distro: Ubuntu 16.04 (xenial) (64bit)
* Desktop Environment: Unity7
* Persepolis Version: 3.2.0.2 (xenial)
* How do you install Persepolis?: ppa:persepolis/ppa repository
* Error log:
 ```
~$ persepolis 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/persepolis/scripts/mainwindow.py", line 55, in <module>
    from persepolis.scripts.video_finder_addlink import VideoFinderAddLink
  File "/usr/lib/python3/dist-packages/persepolis/scripts/video_finder_addlink.py", line 27, in <module>
    import youtube_dl
ImportError: No module named 'youtube_dl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/persepolis", line 11, in <module>
    load_entry_point('persepolis==3.2.0', 'console_scripts', 'persepolis')()
  File "/home/aurelio/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/aurelio/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/home/aurelio/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/home/aurelio/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/persepolis/__main__.py", line 20, in <module>
    from persepolis.scripts import persepolis
  File "/usr/lib/python3/dist-packages/persepolis/scripts/persepolis.py", line 93, in <module>
    from persepolis.scripts.mainwindow import MainWindow
  File "/usr/lib/python3/dist-packages/persepolis/scripts/mainwindow.py", line 57, in <module>
    except ModuleNotFoundError:
NameError: name 'ModuleNotFoundError' is not defined

```
**Issue Description and steps to reproduce:**
Crash during persepolis startup.
 Launched from terminal using `persepolis` string result in the error log above.

**Comment by alireza-amirsamimi** [comment]
Hello
```
sudo apt update
sudo apt install python3-pip
sudo pip3 install youtube-dl
```

**Comment by Aury88** [comment]
Hi! Yes. I've the following  error running  `sudo pip3 install youtube-dl`
```
Traceback (most recent call last):
  File "/usr/bin/pip3", line 9, in <module>
    from pip import main
ImportError: cannot import name 'main'
```

**Comment by alireza-amirsamimi** [comment]
Your system's Python3 is broken.
