### ISSUE TITLE
[BUG] Problem downloading any file

### ISSUE THREAD

**Issue by mrostd** [persepolisdm/persepolis#777]
**System Details:**
* Operating System: Gnu/Linux
* Distro(For GNU/Linux and BSD users): openSUSE Tumbleweed
* Desktop Environment(For GNU/Linux and BSD users): KDE
* Persepolis Version: 3.2.0
* How do you install Persepolis? Repositories

* _Please attach log files if crash or paste error message_
Log File:
===================================================

Persepolis Download Manager, 2020/03/31 01:58:05

2020-03-31 01:58:05,376 - Persepolis - INFO - chrome: Json file is created successfully.

persepolis executer file is created successfully.

2020-03-31 01:58:05,412 - Persepolis - INFO - chromium: Json file is created successfully.

persepolis executer file is created successfully.

2020-03-31 01:58:05,427 - Persepolis - INFO - opera: Json file is created successfully.

persepolis executer file is created successfully.

2020-03-31 01:58:05,439 - Persepolis - INFO - vivaldi: Json file is created successfully.

persepolis executer file is created successfully.

2020-03-31 01:58:05,450 - Persepolis - INFO - firefox: Json file is created successfully.

persepolis executer file is created successfully.

2020-03-31 01:58:14,413 - Persepolis - INFO - youtube_dl version: 2020.03.24

2020-03-31 01:58:14,822 - Persepolis - ERROR - Aria2 didn't respond!

2020-03-31 01:58:14,823 - Persepolis - INFO - Starting Aria2

2020-03-31 01:58:16,509 - Persepolis - INFO - 

**********

ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers

built with gcc 9 (SUSE Linux) configuration: --prefix=/usr

--libdir=/usr/lib64 --shlibdir=/usr/lib64 --incdir=/usr/include/ffmpeg

--extra-cflags='-O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong

-funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection

-Werror=return-type -flto=auto -g' --optflags='-O2 -Wall

-D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables

-fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-

type -flto=auto -g' --disable-htmlpages --enable-pic --disable-

stripping --enable-shared --disable-static --enable-gpl --disable-

openssl --enable-avresample --enable-gnutls --enable-ladspa --enable-

libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-

libcelt --enable-libcdio --enable-libcodec2 --enable-libdav1d

--enable-libdc1394 --enable-libdrm --enable-libfontconfig --enable-

libfreetype --enable-libfribidi --enable-libgsm --enable-libjack

--enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-

libopenmpt --enable-libopus --enable-libpulse --enable-librubberband

--enable-libsoxr --enable-libspeex --enable-libssh --enable-libsrt

--enable-libtheora --enable-libtwolame --enable-libvidstab --enable-

libvorbis --enable-libv4l2 --enable-libvpx --enable-libwebp --enable-

libxml2 --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lto

--enable-lv2 --enable-libmfx --enable-vaapi --enable-vdpau --enable-

libfdk-aac-dlopen --enable-nonfree --enable-libvo-amrwbenc --enable-

version3 --enable-libx264 --enable-libx265 --enable-librtmp --enable-

libxvid libavutil      56. 31.100 / 56. 31.100 libavcodec     58.

54.100 / 58. 54.100 libavformat    58. 29.100 / 58. 29.100 libavdevice

58.  8.100 / 58.  8.100 libavfilter     7. 57.100 /  7. 57.100

libavresample   4.  0.  0 /  4.  0.  0 libswscale      5.  5.100 /  5.

5.100 libswresample   3.  5.100 /  3.  5.100 libpostproc    55.  5.100

/ 55.  5.100

**********

2020-03-31 01:58:16,510 - Persepolis - INFO - python version: 3.8.2 (default, Mar 05 2020, 18:58:42) [GCC]

2020-03-31 01:58:16,510 - Persepolis - INFO - QT version: 5.14.1

2020-03-31 01:58:16,510 - Persepolis - INFO - PyQt version: 5.13.2

2020-03-31 01:58:16,510 - Persepolis - INFO - Operating system: Linux

2020-03-31 01:58:16,510 - Persepolis - INFO - Desktop env.: KDE

2020-03-31 01:58:16,850 - Persepolis - INFO - Aria2 is running

2020-03-31 01:58:16,850 - Persepolis - INFO - Aria2 version: 1.35.0

2020-03-31 01:58:18,487 - Persepolis - ERROR - Spider couldn't find file name

2020-03-31 01:58:20,955 - Persepolis - INFO - 70eb9bdb70895c6c Starts

Persepolis Download Manager, 2020/03/31 01:58:33

2020-03-31 01:58:33,461 - Persepolis - INFO - chrome: Json file is created successfully.

persepolis executer file is created successfully.

2020-03-31 01:58:33,477 - Persepolis - INFO - chromium: Json file is created successfully.

persepolis executer file is created successfully.

2020-03-31 01:58:33,494 - Persepolis - INFO - opera: Json file is created successfully.

persepolis executer file is created successfully.

2020-03-31 01:58:33,511 - Persepolis - INFO - vivaldi: Json file is created successfully.

persepolis executer file is created successfully.

2020-03-31 01:58:33,526 - Persepolis - INFO - firefox: Json file is created successfully.

persepolis executer file is created successfully.

2020-03-31 01:58:34,643 - Persepolis - INFO - youtube_dl version: 2020.03.24

2020-03-31 01:58:34,994 - Persepolis - INFO - Aria2 is running

2020-03-31 01:58:34,994 - Persepolis - INFO - Aria2 version: 1.35.0

2020-03-31 01:58:35,238 - Persepolis - INFO - 

**********

ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers

built with gcc 9 (SUSE Linux) configuration: --prefix=/usr

--libdir=/usr/lib64 --shlibdir=/usr/lib64 --incdir=/usr/include/ffmpeg

--extra-cflags='-O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong

-funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection

-Werror=return-type -flto=auto -g' --optflags='-O2 -Wall

-D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables

-fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-

type -flto=auto -g' --disable-htmlpages --enable-pic --disable-

stripping --enable-shared --disable-static --enable-gpl --disable-

openssl --enable-avresample --enable-gnutls --enable-ladspa --enable-

libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-

libcelt --enable-libcdio --enable-libcodec2 --enable-libdav1d

--enable-libdc1394 --enable-libdrm --enable-libfontconfig --enable-

libfreetype --enable-libfribidi --enable-libgsm --enable-libjack

--enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-

libopenmpt --enable-libopus --enable-libpulse --enable-librubberband

--enable-libsoxr --enable-libspeex --enable-libssh --enable-libsrt

--enable-libtheora --enable-libtwolame --enable-libvidstab --enable-

libvorbis --enable-libv4l2 --enable-libvpx --enable-libwebp --enable-

libxml2 --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lto

--enable-lv2 --enable-libmfx --enable-vaapi --enable-vdpau --enable-

libfdk-aac-dlopen --enable-nonfree --enable-libvo-amrwbenc --enable-

version3 --enable-libx264 --enable-libx265 --enable-librtmp --enable-

libxvid libavutil      56. 31.100 / 56. 31.100 libavcodec     58.

54.100 / 58. 54.100 libavformat    58. 29.100 / 58. 29.100 libavdevice

58.  8.100 / 58.  8.100 libavfilter     7. 57.100 /  7. 57.100

libavresample   4.  0.  0 /  4.  0.  0 libswscale      5.  5.100 /  5.

5.100 libswresample   3.  5.100 /  3.  5.100 libpostproc    55.  5.100

/ 55.  5.100

**********

2020-03-31 01:58:35,239 - Persepolis - INFO - python version: 3.8.2 (default, Mar 05 2020, 18:58:42) [GCC]

2020-03-31 01:58:35,239 - Persepolis - INFO - QT version: 5.14.1

2020-03-31 01:58:35,240 - Persepolis - INFO - PyQt version: 5.13.2

2020-03-31 01:58:35,240 - Persepolis - INFO - Operating system: Linux

2020-03-31 01:58:35,240 - Persepolis - INFO - Desktop env.: KDE

2020-03-31 02:11:49,748 - Persepolis - INFO - None paused

===================================================

Persepolis Download Manager, 2020/03/31 02:11:59

2020-03-31 02:11:59,710 - Persepolis - INFO - chrome: Json file is created successfully.

persepolis executer file is created successfully.

2020-03-31 02:11:59,720 - Persepolis - INFO - chromium: Json file is created successfully.

persepolis executer file is created successfully.

2020-03-31 02:11:59,731 - Persepolis - INFO - opera: Json file is created successfully.

persepolis executer file is created successfully.

2020-03-31 02:11:59,742 - Persepolis - INFO - vivaldi: Json file is created successfully.

persepolis executer file is created successfully.

2020-03-31 02:11:59,753 - Persepolis - INFO - firefox: Json file is created successfully.

persepolis executer file is created successfully.

2020-03-31 02:12:00,833 - Persepolis - INFO - youtube_dl version: 2020.03.24

2020-03-31 02:12:01,173 - Persepolis - INFO - Aria2 is running

2020-03-31 02:12:01,173 - Persepolis - INFO - Aria2 version: 1.35.0

2020-03-31 02:12:01,375 - Persepolis - INFO - 

**********

ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers

built with gcc 9 (SUSE Linux) configuration: --prefix=/usr

--libdir=/usr/lib64 --shlibdir=/usr/lib64 --incdir=/usr/include/ffmpeg

--extra-cflags='-O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong

-funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection

-Werror=return-type -flto=auto -g' --optflags='-O2 -Wall

-D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables

-fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-

type -flto=auto -g' --disable-htmlpages --enable-pic --disable-

stripping --enable-shared --disable-static --enable-gpl --disable-

openssl --enable-avresample --enable-gnutls --enable-ladspa --enable-

libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-

libcelt --enable-libcdio --enable-libcodec2 --enable-libdav1d

--enable-libdc1394 --enable-libdrm --enable-libfontconfig --enable-

libfreetype --enable-libfribidi --enable-libgsm --enable-libjack

--enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-

libopenmpt --enable-libopus --enable-libpulse --enable-librubberband

--enable-libsoxr --enable-libspeex --enable-libssh --enable-libsrt

--enable-libtheora --enable-libtwolame --enable-libvidstab --enable-

libvorbis --enable-libv4l2 --enable-libvpx --enable-libwebp --enable-

libxml2 --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lto

--enable-lv2 --enable-libmfx --enable-vaapi --enable-vdpau --enable-

libfdk-aac-dlopen --enable-nonfree --enable-libvo-amrwbenc --enable-

version3 --enable-libx264 --enable-libx265 --enable-librtmp --enable-

libxvid libavutil      56. 31.100 / 56. 31.100 libavcodec     58.

54.100 / 58. 54.100 libavformat    58. 29.100 / 58. 29.100 libavdevice

58.  8.100 / 58.  8.100 libavfilter     7. 57.100 /  7. 57.100

libavresample   4.  0.  0 /  4.  0.  0 libswscale      5.  5.100 /  5.

5.100 libswresample   3.  5.100 /  3.  5.100 libpostproc    55.  5.100

/ 55.  5.100

**********

2020-03-31 02:12:01,376 - Persepolis - INFO - python version: 3.8.2 (default, Mar 05 2020, 18:58:42) [GCC]

2020-03-31 02:12:01,376 - Persepolis - INFO - QT version: 5.14.1

2020-03-31 02:12:01,376 - Persepolis - INFO - PyQt version: 5.13.2

2020-03-31 02:12:01,376 - Persepolis - INFO - Operating system: Linux

2020-03-31 02:12:01,376 - Persepolis - INFO - Desktop env.: KDE

2020-03-31 02:12:10,767 - Persepolis - ERROR - Download did not start

2020-03-31 02:12:10,768 - Persepolis - ERROR - Traceback (most recent call last):

  File "/usr/lib/python3.8/site-packages/persepolis/scripts/download.py", line 284, in downloadAria

    answer = server.aria2.addUri([link], aria_dict)

  File "/usr/lib64/python3.8/xmlrpc/client.py", line 1109, in __call__

    return self.__send(self.__name, args)

  File "/usr/lib64/python3.8/xmlrpc/client.py", line 1450, in __request

    response = self.__transport.request(

  File "/usr/lib64/python3.8/xmlrpc/client.py", line 1153, in request

    return self.single_request(host, handler, request_body, verbose)

  File "/usr/lib64/python3.8/xmlrpc/client.py", line 1169, in single_request

    return self.parse_response(resp)

  File "/usr/lib64/python3.8/xmlrpc/client.py", line 1341, in parse_response

    return u.close()

  File "/usr/lib64/python3.8/xmlrpc/client.py", line 655, in close

    raise Fault(**self._stack[0])

xmlrpc.client.Fault: <Fault 1: 'No URI to download.'>

2020-03-31 02:12:11,443 - Persepolis - INFO - Download complete - GID : 70eb9bdb70895c6c

Persepolis Download Manager, 2020/03/31 02:12:22

2020-03-31 02:12:22,884 - Persepolis - INFO - chrome: Json file is created successfully.

persepolis executer file is created successfully.

2020-03-31 02:12:22,895 - Persepolis - INFO - chromium: Json file is created successfully.

persepolis executer file is created successfully.

2020-03-31 02:12:22,906 - Persepolis - INFO - opera: Json file is created successfully.

persepolis executer file is created successfully.

2020-03-31 02:12:22,919 - Persepolis - INFO - vivaldi: Json file is created successfully.

persepolis executer file is created successfully.

2020-03-31 02:12:22,930 - Persepolis - INFO - firefox: Json file is created successfully.

persepolis executer file is created successfully.

2020-03-31 02:12:24,135 - Persepolis - INFO - youtube_dl version: 2020.03.24

2020-03-31 02:12:24,509 - Persepolis - INFO - Aria2 is running

2020-03-31 02:12:24,509 - Persepolis - INFO - Aria2 version: 1.35.0

2020-03-31 02:12:24,677 - Persepolis - INFO - 

**********

ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers

built with gcc 9 (SUSE Linux) configuration: --prefix=/usr

--libdir=/usr/lib64 --shlibdir=/usr/lib64 --incdir=/usr/include/ffmpeg

--extra-cflags='-O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong

-funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection

-Werror=return-type -flto=auto -g' --optflags='-O2 -Wall

-D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables

-fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-

type -flto=auto -g' --disable-htmlpages --enable-pic --disable-

stripping --enable-shared --disable-static --enable-gpl --disable-

openssl --enable-avresample --enable-gnutls --enable-ladspa --enable-

libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-

libcelt --enable-libcdio --enable-libcodec2 --enable-libdav1d

--enable-libdc1394 --enable-libdrm --enable-libfontconfig --enable-

libfreetype --enable-libfribidi --enable-libgsm --enable-libjack

--enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-

libopenmpt --enable-libopus --enable-libpulse --enable-librubberband

--enable-libsoxr --enable-libspeex --enable-libssh --enable-libsrt

--enable-libtheora --enable-libtwolame --enable-libvidstab --enable-

libvorbis --enable-libv4l2 --enable-libvpx --enable-libwebp --enable-

libxml2 --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lto

--enable-lv2 --enable-libmfx --enable-vaapi --enable-vdpau --enable-

libfdk-aac-dlopen --enable-nonfree --enable-libvo-amrwbenc --enable-

version3 --enable-libx264 --enable-libx265 --enable-librtmp --enable-

libxvid libavutil      56. 31.100 / 56. 31.100 libavcodec     58.

54.100 / 58. 54.100 libavformat    58. 29.100 / 58. 29.100 libavdevice

58.  8.100 / 58.  8.100 libavfilter     7. 57.100 /  7. 57.100

libavresample   4.  0.  0 /  4.  0.  0 libswscale      5.  5.100 /  5.

5.100 libswresample   3.  5.100 /  3.  5.100 libpostproc    55.  5.100

/ 55.  5.100

**********

2020-03-31 02:12:24,677 - Persepolis - INFO - python version: 3.8.2 (default, Mar 05 2020, 18:58:42) [GCC]

2020-03-31 02:12:24,677 - Persepolis - INFO - QT version: 5.14.1

2020-03-31 02:12:24,677 - Persepolis - INFO - PyQt version: 5.13.2

2020-03-31 02:12:24,677 - Persepolis - INFO - Operating system: Linux

2020-03-31 02:12:24,678 - Persepolis - INFO - Desktop env.: KDE

**Issue Description and steps to reproduce:**
سلام- میدونم باید انگلیسی بنویسم، اما انقدری گسترده و پیچ در پیچه که نمیدونم چی باید بگم.
پرسپولیس روی اپن سوزه، هنگام دانلود هر چیزی روی 99٪ گیر میکنه.
بدون هیچ گونه ارور خاصی، برای این که کار کنه مجبورم دانلود رو استاپ و مجددا 
Resume
کنم.
مشکل دوم: وقتی تو مشکل بالا دانلود رو استاپ میکنم، پرسپولیس بسته میشه کاملا (چه از سیستم ترای و چه پنجرش)

**Comment by laksh225** [comment]
Could you write the issue description in English?
