### ISSUE TITLE
Persepolis startup fail

### ISSUE THREAD

**Issue by saeed860** [persepolisdm/persepolis#795]
**System Details:**
* Operating System:  LINUX 5.4 X64
* Distro(For GNU/Linux and BSD users): ubuntu 20.04 LTS
* Desktop Environment(For GNU/Linux and BSD users): UBUNTU STUDIO
* Persepolis Version: 
* How do you install Persepolis? (Repositories, source, ...) from APPER software store

* _Please attach log files if crash or paste error message_
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/persepolis/scripts/persepolis.py", line 400, in main
    mainwindow = MainWindow(start_in_tray, persepolis_download_manager, persepolis_download_manager.setting)
  File "/usr/lib/python3/dist-packages/persepolis/scripts/mainwindow.py", line 883, in __init__
    self.persepolis_db.setDBTablesToDefaultValue()
  File "/usr/lib/python3/dist-packages/persepolis/scripts/data_base.py", line 1122, in setDBTablesToDefaultValue
    self.persepolis_db_cursor.execute("""UPDATE addlink_db_table SET start_time = NULL,
sqlite3.OperationalError: disk I/O error

**Issue Description and steps to reproduce:**
the Persepolis download manager didnt run and show me that message then i posted here.
thanks
![persepolis](https://user-images.githubusercontent.com/63933384/85075543-a7397d80-b1d3-11ea-8bfb-b9e90285a7fa.jpg)

**Comment by itisrasoul** [comment]
@saeed860 It seems it has something to do with sqlite3 timing issue while loading some database files. Reinstalling the persepolis *may* solve this problem; I'm not quite sure about it.
