### ISSUE TITLE
Persepolis crash

### ISSUE THREAD

**Issue by LeoJF300** [persepolisdm/persepolis#826]
Linux
Fedora 32
Gnome

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/persepolis/scripts/persepolis.py", line 433, in main
    mainwindow = MainWindow(start_in_tray, persepolis_download_manager, persepolis_download_manager.setting)
  File "/usr/lib/python3.8/site-packages/persepolis/scripts/mainwindow.py", line 1350, in __init__
    dict = download_table_dict[gid]
KeyError: '8a6f982e454005bd'

**Comment by SuperKaninchen** [comment]
I just downloaded it again on Fedora 32 and it works without any problems. How did you install it and when exactly does the error occur?
