### ISSUE TITLE
not open in arch linux

### ISSUE THREAD

**Issue by MOHAMED19OS** [persepolisdm/persepolis#840]
**System Details:**
* Operating System: Arch Linux
* Distro(For GNU/Linux and BSD users): ?
* Desktop Environment(For GNU/Linux and BSD users): KDE 5.77.0 / Plasma 5.20.4
* Persepolis Version: Persepolis Download Manager 3.2.0
* How do you install Persepolis? (Repositories)

* `Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/persepolis/scripts/persepolis.py", line 433, in main
    mainwindow = MainWindow(start_in_tray, persepolis_download_manager, persepolis_download_manager.setting)
  File "/usr/lib/python3.9/site-packages/persepolis/scripts/mainwindow.py", line 1306, in __init__
    self.persepolis_db.setDBTablesToDefaultValue()
  File "/usr/lib/python3.9/site-packages/persepolis/scripts/data_base.py", line 1144, in setDBTablesToDefaultValue
    self.persepolis_db_cursor.execute("""UPDATE download_db_table SET status = 'stopped'
sqlite3.DatabaseError: database disk image is malformed`

**Comment by lnxpy** [comment]
Hey Mohammad,
Remove all dependent DBs (Don't forget to remove all cached DBs) and try again.

**Comment by SayanChakroborty** [comment]
Same issue but slightly different traceback output:
`Traceback (most recent call last):
    File "/usr/bin/persepolis", line 33, in <module>
        sys.exit(load_entry_point('persepolis==3.2.0', 'console_scripts', 'persepolis')())
    File "/usr/bin/persepolis", line 25, in importlib_load_entry_point
        return next(matches).load()
    File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
        module = import_module(match.group('module'))
    File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
    File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
    File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 855, in exec_module
    File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
    File "/usr/lib/python3.9/site-packages/persepolis/__main__.py", line 20, in <module>
        from persepolis.scripts import persepolis
    File "/usr/lib/python3.9/site-packages/persepolis/scripts/persepolis.py", line 93, in <module>
        from persepolis.scripts.mainwindow import MainWindow
    File "/usr/lib/python3.9/site-packages/persepolis/scripts/mainwindow.py", line 26, in <module>
        from persepolis.scripts.setting import PreferencesWindow
    File "/usr/lib/python3.9/site-packages/persepolis/scripts/setting.py", line 18, in <module>
        from persepolis.gui.setting_ui import Setting_Ui, KeyCapturingWindow_Ui
    File "/usr/lib/python3.9/site-packages/persepolis/gui/setting_ui.py", line 22, in <module>
        import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
`

Persepolis Version: 3.2.0.-6
OS: Arch Linux
Kernel: 5.12.6-arch1-1
Python Version: 3.9.5
