### ISSUE TITLE
[status=403] I am unable to resume my download after error status on persepolis

### ISSUE THREAD

**Issue by rofibins** [persepolisdm/persepolis#847]
**System Details:**
* Operating System: **Linux**
* Distro(For GNU/Linux and BSD users): **Zorin 15**
* Desktop Environment(For GNU/Linux and BSD users): **XFCE**
* Persepolis Version: **Persepolis Download Manager Newer ver 3.2.0**
* How do you install Persepolis? (Repositories, source, ...) command
sudo add-apt-repository ppa:persepolis/ppa
sudo apt update
sudo apt install persepolis

* _Please attach log files if crash or paste error message_

**Issue Description and steps to reproduce:**

:'(
**I am unable to resume my download after error status on persepolis**
I download windows 10 on their official link
The download file running perfect till 84% which is 4.8 out of 5.7 GB omg :'( duno what to do
Network: normal

Here is on persepolis:
 https://software-download.microsoft.com/sg/Win10_20H2_v2_EnglishInternational_x64.iso?t=0047f994-f72f-45f6-a6f0-c9217e4768ad&e=1611463910&h=b322dfd1f678a939cfeeeff6aa6dea99

Here is the log after several trial:

===================================================

Persepolis Download Manager, 2021/01/24 10:54:06

2021-01-24 10:54:08,083 - Persepolis - INFO - chrome: Json file is created successfully.

persepolis executer file is created successfully.

Thanks for your help.
Rgds,

2021-01-24 10:54:08,091 - Persepolis - INFO - chromium: Json file is created successfully.

persepolis executer file is created successfully.

2021-01-24 10:54:08,098 - Persepolis - INFO - opera: Json file is created successfully.

persepolis executer file is created successfully.

2021-01-24 10:54:08,105 - Persepolis - INFO - vivaldi: Json file is created successfully.

persepolis executer file is created successfully.

2021-01-24 10:54:08,132 - Persepolis - INFO - firefox: Json file is created successfully.

persepolis executer file is created successfully.

2021-01-24 10:54:14,223 - Persepolis - INFO - youtube_dl version: 2018.03.14

2021-01-24 10:54:18,971 - Persepolis - ERROR - Aria2 didn't respond!

2021-01-24 10:54:18,971 - Persepolis - INFO - Starting Aria2

2021-01-24 10:54:21,262 - Persepolis - INFO - Aria2 is running

2021-01-24 10:54:21,263 - Persepolis - INFO - Aria2 version: 1.33.1

2021-01-24 10:54:28,315 - Persepolis - INFO - 

**********

ffmpeg version 3.4.8-0ubuntu0.2 Copyright (c) 2000-2020 the FFmpeg

developers built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)

configuration: --prefix=/usr --extra-version=0ubuntu0.2

--toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu

--incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-

stripping --enable-avresample --enable-avisynth --enable-gnutls

--enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b

--enable-libcaca --enable-libcdio --enable-libflite --enable-

libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme

--enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-

libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse

--enable-librubberband --enable-librsvg --enable-libshine --enable-

libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-

libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx

--enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2

--enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx

--enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394

--enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-

frei0r --enable-libopencv --enable-libx264 --enable-shared libavutil

55. 78.100 / 55. 78.100 libavcodec     57.107.100 / 57.107.100

libavformat    57. 83.100 / 57. 83.100 libavdevice    57. 10.100 / 57.

10.100 libavfilter     6.107.100 /  6.107.100 libavresample   3.  7.

0 /  3.  7.  0 libswscale      4.  8.100 /  4.  8.100 libswresample

2.  9.100 /  2.  9.100 libpostproc    54.  7.100 / 54.  7.100

**********

2021-01-24 10:54:28,316 - Persepolis - INFO - python version: 3.6.9 (default, Oct  8 2020, 12:12:24) 

[GCC 8.4.0]

2021-01-24 10:54:28,316 - Persepolis - INFO - QT version: 5.9.5

2021-01-24 10:54:28,316 - Persepolis - INFO - PyQt version: 5.10.1

2021-01-24 10:54:28,316 - Persepolis - INFO - Operating system: Linux

2021-01-24 10:54:28,316 - Persepolis - INFO - Desktop env.: XFCE

2021-01-24 10:55:15,403 - Persepolis - ERROR - Download did not start

2021-01-24 10:55:15,427 - Persepolis - ERROR - Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/persepolis/scripts/download.py", line 284, in downloadAria

    answer = server.aria2.addUri([link], aria_dict)

  File "/usr/lib/python3.6/xmlrpc/client.py", line 1112, in __call__

    return self.__send(self.__name, args)

  File "/usr/lib/python3.6/xmlrpc/client.py", line 1452, in __request

    verbose=self.__verbose

  File "/usr/lib/python3.6/xmlrpc/client.py", line 1154, in request

    return self.single_request(host, handler, request_body, verbose)

  File "/usr/lib/python3.6/xmlrpc/client.py", line 1166, in single_request

    http_conn = self.send_request(host, handler, request_body, verbose)

  File "/usr/lib/python3.6/xmlrpc/client.py", line 1272, in send_request

    connection.putrequest("POST", handler, skip_accept_encoding=True)

  File "/usr/lib/python3.6/http/client.py", line 1124, in putrequest

    raise CannotSendRequest(self.__state)

http.client.CannotSendRequest: Request-sent

2021-01-24 10:55:16,290 - Persepolis - ERROR - Download failed - GID : 25667c79dae4e09b- Message : Error

2021-01-24 10:56:12,479 - Persepolis - INFO - a1c261054834b1f8 Starts

2021-01-24 10:57:16,255 - Persepolis - INFO - a1c261054834b1f8 paused

2021-01-24 10:57:17,458 - Persepolis - INFO - a1c261054834b1f8 unpaused

2021-01-24 11:14:01,331 - Persepolis - INFO - a1c261054834b1f8 paused

2021-01-24 11:17:26,087 - Persepolis - INFO - a1c261054834b1f8 unpaused

2021-01-24 11:28:48,707 - Persepolis - INFO - 4de3d049ef9645bf Starts

2021-01-24 11:41:26,268 - Persepolis - INFO - Download complete - GID : 4de3d049ef9645bf

2021-01-24 12:57:46,204 - Persepolis - ERROR - Download failed - GID : a1c261054834b1f8- Message : No URI available.

2021-01-24 12:58:24,264 - Persepolis - ERROR - Download did not start

2021-01-24 12:58:24,370 - Persepolis - ERROR - Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/persepolis/scripts/download.py", line 284, in downloadAria

    answer = server.aria2.addUri([link], aria_dict)

  File "/usr/lib/python3.6/xmlrpc/client.py", line 1112, in __call__

    return self.__send(self.__name, args)

  File "/usr/lib/python3.6/xmlrpc/client.py", line 1452, in __request

    verbose=self.__verbose

  File "/usr/lib/python3.6/xmlrpc/client.py", line 1154, in request

    return self.single_request(host, handler, request_body, verbose)

  File "/usr/lib/python3.6/xmlrpc/client.py", line 1166, in single_request

    http_conn = self.send_request(host, handler, request_body, verbose)

  File "/usr/lib/python3.6/xmlrpc/client.py", line 1272, in send_request

    connection.putrequest("POST", handler, skip_accept_encoding=True)

  File "/usr/lib/python3.6/http/client.py", line 1124, in putrequest

    raise CannotSendRequest(self.__state)

http.client.CannotSendRequest: Request-sent

2021-01-24 12:58:24,838 - Persepolis - ERROR - Download failed - GID : a1c261054834b1f8- Message : Error

2021-01-24 12:58:32,055 - Persepolis - INFO - a1c261054834b1f8 Starts

2021-01-24 12:58:32,441 - Persepolis - ERROR - Download failed - GID : a1c261054834b1f8- Message : The response status is not successful. status=403

2021-01-24 12:58:38,441 - Persepolis - INFO - a1c261054834b1f8 Starts

2021-01-24 12:58:38,694 - Persepolis - ERROR - Download failed - GID : a1c261054834b1f8- Message : The response status is not successful. status=403

2021-01-24 12:58:42,977 - Persepolis - INFO - a1c261054834b1f8 Starts

2021-01-24 12:58:43,431 - Persepolis - ERROR - Download failed - GID : a1c261054834b1f8- Message : The response status is not successful. status=403

2021-01-24 12:58:45,671 - Persepolis - INFO - a1c261054834b1f8 Starts

2021-01-24 12:58:45,672 - Persepolis - ERROR - Aria2 didn't respond!

2021-01-24 12:58:45,672 - Persepolis - ERROR - Aria2 didn't respond!

2021-01-24 12:58:47,707 - Persepolis - INFO - Reconnecting Aria2 ...

2021-01-24 12:58:47,713 - Persepolis - INFO - Persepolis reconnected aria2 successfully

2021-01-24 12:58:47,901 - Persepolis - ERROR - Download did not start

2021-01-24 12:58:47,902 - Persepolis - ERROR - Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/persepolis/scripts/download.py", line 284, in downloadAria

    answer = server.aria2.addUri([link], aria_dict)

  File "/usr/lib/python3.6/xmlrpc/client.py", line 1112, in __call__

    return self.__send(self.__name, args)

  File "/usr/lib/python3.6/xmlrpc/client.py", line 1452, in __request

    verbose=self.__verbose

  File "/usr/lib/python3.6/xmlrpc/client.py", line 1154, in request

    return self.single_request(host, handler, request_body, verbose)

  File "/usr/lib/python3.6/xmlrpc/client.py", line 1170, in single_request

    return self.parse_response(resp)

  File "/usr/lib/python3.6/xmlrpc/client.py", line 1342, in parse_response

    return u.close()

  File "/usr/lib/python3.6/xmlrpc/client.py", line 656, in close

    raise Fault(**self._stack[0])

xmlrpc.client.Fault: <Fault 1: 'No URI to download.'>

2021-01-24 12:58:48,005 - Persepolis - ERROR - Download failed - GID : a1c261054834b1f8- Message : The response status is not successful. status=403

2021-01-24 12:59:44,586 - Persepolis - INFO - a1c261054834b1f8 Starts

2021-01-24 12:59:45,173 - Persepolis - ERROR - Download failed - GID : a1c261054834b1f8- Message : Failed to connect to the host 117.18.232.200, cause: Network is unreachable

2021-01-24 12:59:47,103 - Persepolis - INFO - a1c261054834b1f8 Starts

2021-01-24 12:59:47,552 - Persepolis - ERROR - Download failed - GID : a1c261054834b1f8- Message : CUID#119 - Name resolution for software-download.microsoft.com failed:Could not contact DNS servers

2021-01-24 12:59:48,561 - Persepolis - INFO - a1c261054834b1f8 Starts

2021-01-24 12:59:48,770 - Persepolis - ERROR - Download failed - GID : a1c261054834b1f8- Message : CUID#120 - Name resolution for software-download.microsoft.com failed:Could not contact DNS servers

2021-01-24 12:59:50,942 - Persepolis - INFO - a1c261054834b1f8 Starts

2021-01-24 12:59:51,713 - Persepolis - ERROR - Download failed - GID : a1c261054834b1f8- Message : CUID#121 - Name resolution for software-download.microsoft.com failed:Could not contact DNS servers

2021-01-24 12:59:55,855 - Persepolis - INFO - a1c261054834b1f8 Starts

2021-01-24 12:59:56,367 - Persepolis - ERROR - Download failed - GID : a1c261054834b1f8- Message : CUID#122 - Name resolution for software-download.microsoft.com failed:Could not contact DNS servers

2021-01-24 13:00:30,156 - Persepolis - INFO - a1c261054834b1f8 Starts

2021-01-24 13:00:30,668 - Persepolis - ERROR - Download failed - GID : a1c261054834b1f8- Message : The response status is not successful. status=403

2021-01-24 13:00:32,190 - Persepolis - INFO - a1c261054834b1f8 Starts

2021-01-24 13:00:32,723 - Persepolis - ERROR - Download failed - GID : a1c261054834b1f8- Message : The response status is not successful. status=403

2021-01-24 13:00:33,981 - Persepolis - INFO - a1c261054834b1f8 Starts

2021-01-24 13:00:34,456 - Persepolis - ERROR - Download failed - GID : a1c261054834b1f8- Message : The response status is not successful. status=403

2021-01-24 13:00:35,206 - Persepolis - INFO - a1c261054834b1f8 Starts

2021-01-24 13:00:35,657 - Persepolis - ERROR - Download failed - GID : a1c261054834b1f8- Message : The response status is not successful. status=403

2021-01-24 13:00:36,432 - Persepolis - INFO - a1c261054834b1f8 Starts

2021-01-24 13:00:37,094 - Persepolis - ERROR - Download failed - GID : a1c261054834b1f8- Message : The response status is not successful. status=403

2021-01-24 13:00:37,955 - Persepolis - INFO - a1c261054834b1f8 Starts

2021-01-24 13:00:38,771 - Persepolis - ERROR - Download failed - GID : a1c261054834b1f8- Message : The response status is not successful. status=403

2021-01-24 13:01:28,625 - Persepolis - INFO - a1c261054834b1f8 Starts

2021-01-24 13:01:29,245 - Persepolis - ERROR - Download failed - GID : a1c261054834b1f8- Message : The response status is not successful. status=403

2021-01-24 13:01:32,003 - Persepolis - INFO - a1c261054834b1f8 Starts

2021-01-24 13:01:32,510 - Persepolis - ERROR - Download failed - GID : a1c261054834b1f8- Message : The response status is not successful. status=403

2021-01-24 13:02:06,942 - Persepolis - INFO - a1c261054834b1f8 Starts

2021-01-24 13:02:07,496 - Persepolis - ERROR - Download failed - GID : a1c261054834b1f8- Message : The response status is not successful. status=403

2021-01-24 13:02:08,788 - Persepolis - INFO - a1c261054834b1f8 Starts

2021-01-24 13:02:09,189 - Persepolis - ERROR - Download failed - GID : a1c261054834b1f8- Message : The response status is not successful. status=403

2021-01-24 13:02:10,196 - Persepolis - INFO - a1c261054834b1f8 Starts

2021-01-24 13:02:10,482 - Persepolis - ERROR - Download failed - GID : a1c261054834b1f8- Message : The response status is not successful. status=403

2021-01-24 13:02:11,247 - Persepolis - INFO - a1c261054834b1f8 Starts

2021-01-24 13:02:12,091 - Persepolis - ERROR - Download failed - GID : a1c261054834b1f8- Message : The response status is not successful. status=403

2021-01-24 13:02:12,920 - Persepolis - INFO - a1c261054834b1f8 Starts

2021-01-24 13:02:13,600 - Persepolis - ERROR - Download failed - GID : a1c261054834b1f8- Message : The response status is not successful. status=403

2021-01-24 13:02:16,472 - Persepolis - INFO - a1c261054834b1f8 Starts

2021-01-24 13:02:16,997 - Persepolis - ERROR - Download failed - GID : a1c261054834b1f8- Message : The response status is not successful. status=403

2021-01-24 13:02:18,601 - Persepolis - INFO - a1c261054834b1f8 Starts

2021-01-24 13:02:19,142 - Persepolis - ERROR - Download failed - GID : a1c261054834b1f8- Message : The response status is not successful. status=403

2021-01-24 13:02:49,755 - Persepolis - INFO - a1c261054834b1f8 Starts

2021-01-24 13:02:50,385 - Persepolis - ERROR - Download failed - GID : a1c261054834b1f8- Message : The response status is not successful. status=403

2021-01-24 13:02:51,452 - Persepolis - INFO - a1c261054834b1f8 Starts

2021-01-24 13:02:52,059 - Persepolis - ERROR - Download failed - GID : a1c261054834b1f8- Message : The response status is not successful. status=403

2021-01-24 13:02:53,167 - Persepolis - INFO - a1c261054834b1f8 Starts

2021-01-24 13:02:53,759 - Persepolis - ERROR - Download failed - GID : a1c261054834b1f8- Message : The response status is not successful. status=403

2021-01-24 13:02:54,847 - Persepolis - INFO - a1c261054834b1f8 Starts

2021-01-24 13:02:55,458 - Persepolis - ERROR - Download failed - GID : a1c261054834b1f8- Message : The response status is not successful. status=403

2021-01-24 13:04:33,724 - Persepolis - ERROR - Download did not start

2021-01-24 13:04:33,741 - Persepolis - ERROR - Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/persepolis/scripts/download.py", line 284, in downloadAria

    answer = server.aria2.addUri([link], aria_dict)

  File "/usr/lib/python3.6/xmlrpc/client.py", line 1112, in __call__

    return self.__send(self.__name, args)

  File "/usr/lib/python3.6/xmlrpc/client.py", line 1452, in __request

    verbose=self.__verbose

  File "/usr/lib/python3.6/xmlrpc/client.py", line 1154, in request

    return self.single_request(host, handler, request_body, verbose)

  File "/usr/lib/python3.6/xmlrpc/client.py", line 1167, in single_request

    resp = http_conn.getresponse()

  File "/usr/lib/python3.6/http/client.py", line 1363, in getresponse

    raise ResponseNotReady(self.__state)

http.client.ResponseNotReady: Idle

2021-01-24 13:04:34,426 - Persepolis - ERROR - Download failed - GID : a1c261054834b1f8- Message : The response status is not successful. status=403

2021-01-24 13:04:39,572 - Persepolis - INFO - a1c261054834b1f8 Starts

2021-01-24 13:04:40,555 - Persepolis - ERROR - Download failed - GID : a1c261054834b1f8- Message : The response status is not successful. status=403

2021-01-24 13:06:57,962 - Persepolis - INFO - a1c261054834b1f8 Starts

2021-01-24 13:06:58,504 - Persepolis - ERROR - Download failed - GID : a1c261054834b1f8- Message : The response status is not successful. status=403

2021-01-24 13:07:32,892 - Persepolis - INFO - a1c261054834b1f8 Starts

2021-01-24 13:07:33,348 - Persepolis - ERROR - Download failed - GID : a1c261054834b1f8- Message : The response status is not successful. status=403

2021-01-24 13:08:53,525 - Persepolis - INFO - a1c261054834b1f8 Starts

2021-01-24 13:08:54,232 - Persepolis - ERROR - Download failed - GID : a1c261054834b1f8- Message : The response status is not successful. status=403

2021-01-24 13:09:01,416 - Persepolis - INFO - a1c261054834b1f8 Starts

2021-01-24 13:09:01,749 - Persepolis - ERROR - Download failed - GID : a1c261054834b1f8- Message : The response status is not successful. status=403

2021-01-24 13:09:03,534 - Persepolis - INFO - a1c261054834b1f8 Starts

2021-01-24 13:09:04,048 - Persepolis - ERROR - Download failed - GID : a1c261054834b1f8- Message : The response status is not successful. status=403

2021-01-24 13:09:04,991 - Persepolis - INFO - a1c261054834b1f8 Starts

2021-01-24 13:09:05,814 - Persepolis - ERROR - Download failed - GID : a1c261054834b1f8- Message : The response status is not successful. status=403

2021-01-24 13:09:06,796 - Persepolis - INFO - a1c261054834b1f8 Starts

2021-01-24 13:09:07,133 - Persepolis - ERROR - Download failed - GID : a1c261054834b1f8- Message : The response status is not successful. status=403

2021-01-24 13:09:08,734 - Persepolis - INFO - a1c261054834b1f8 Starts

2021-01-24 13:09:09,237 - Persepolis - ERROR - Download failed - GID : a1c261054834b1f8- Message : The response status is not successful. status=403

2021-01-24 13:09:10,522 - Persepolis - INFO - a1c261054834b1f8 Starts

2021-01-24 13:09:10,897 - Persepolis - ERROR - Download failed - GID : a1c261054834b1f8- Message : The response status is not successful. status=403

2021-01-24 13:09:13,429 - Persepolis - INFO - a1c261054834b1f8 Starts

2021-01-24 13:09:14,086 - Persepolis - ERROR - Download failed - GID : a1c261054834b1f8- Message : The response status is not successful. status=403

2021-01-24 13:09:15,183 - Persepolis - INFO - a1c261054834b1f8 Starts

2021-01-24 13:09:15,677 - Persepolis - ERROR - Download failed - GID : a1c261054834b1f8- Message : The response status is not successful. status=403

===================================================

Persepolis Download Manager, 2021/01/24 13:12:22

2021-01-24 13:12:23,380 - Persepolis - INFO - chrome: Json file is created successfully.

persepolis executer file is created successfully.

2021-01-24 13:12:23,391 - Persepolis - INFO - chromium: Json file is created successfully.

persepolis executer file is created successfully.

2021-01-24 13:12:23,398 - Persepolis - INFO - opera: Json file is created successfully.

persepolis executer file is created successfully.

2021-01-24 13:12:23,407 - Persepolis - INFO - vivaldi: Json file is created successfully.

persepolis executer file is created successfully.

2021-01-24 13:12:23,443 - Persepolis - INFO - firefox: Json file is created successfully.

persepolis executer file is created successfully.

2021-01-24 13:12:25,947 - Persepolis - INFO - youtube_dl version: 2018.03.14

2021-01-24 13:12:27,161 - Persepolis - ERROR - Aria2 didn't respond!

2021-01-24 13:12:27,162 - Persepolis - INFO - Starting Aria2

2021-01-24 13:12:29,236 - Persepolis - INFO - Aria2 is running

2021-01-24 13:12:29,237 - Persepolis - INFO - Aria2 version: 1.33.1

2021-01-24 13:12:29,690 - Persepolis - INFO - 

**********

ffmpeg version 3.4.8-0ubuntu0.2 Copyright (c) 2000-2020 the FFmpeg

developers built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)

configuration: --prefix=/usr --extra-version=0ubuntu0.2

--toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu

--incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-

stripping --enable-avresample --enable-avisynth --enable-gnutls

--enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b

--enable-libcaca --enable-libcdio --enable-libflite --enable-

libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme

--enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-

libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse

--enable-librubberband --enable-librsvg --enable-libshine --enable-

libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-

libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx

--enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2

--enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx

--enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394

--enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-

frei0r --enable-libopencv --enable-libx264 --enable-shared libavutil

55. 78.100 / 55. 78.100 libavcodec     57.107.100 / 57.107.100

libavformat    57. 83.100 / 57. 83.100 libavdevice    57. 10.100 / 57.

10.100 libavfilter     6.107.100 /  6.107.100 libavresample   3.  7.

0 /  3.  7.  0 libswscale      4.  8.100 /  4.  8.100 libswresample

2.  9.100 /  2.  9.100 libpostproc    54.  7.100 / 54.  7.100

**********

2021-01-24 13:12:29,691 - Persepolis - INFO - python version: 3.6.9 (default, Oct  8 2020, 12:12:24) 

[GCC 8.4.0]

2021-01-24 13:12:29,691 - Persepolis - INFO - QT version: 5.9.5

2021-01-24 13:12:29,691 - Persepolis - INFO - PyQt version: 5.10.1

2021-01-24 13:12:29,691 - Persepolis - INFO - Operating system: Linux

2021-01-24 13:12:29,691 - Persepolis - INFO - Desktop env.: XFCE

2021-01-24 13:12:37,210 - Persepolis - INFO - a1c261054834b1f8 Starts

2021-01-24 13:12:37,849 - Persepolis - ERROR - Download failed - GID : a1c261054834b1f8- Message : The response status is not successful. status=403

2021-01-24 13:26:19,861 - Persepolis - INFO - a1c261054834b1f8 Starts

2021-01-24 13:26:20,396 - Persepolis - ERROR - Download failed - GID : a1c261054834b1f8- Message : The response status is not successful. status=403

2021-01-24 13:26:21,575 - Persepolis - INFO - a1c261054834b1f8 Starts

2021-01-24 13:26:22,120 - Persepolis - ERROR - Download failed - GID : a1c261054834b1f8- Message : The response status is not successful. status=403

2021-01-24 13:35:09,219 - Persepolis - INFO - a1c261054834b1f8 Starts

2021-01-24 13:35:09,640 - Persepolis - ERROR - Download failed - GID : a1c261054834b1f8- Message : The response status is not successful. status=403

2021-01-24 13:35:10,452 - Persepolis - INFO - a1c261054834b1f8 Starts

2021-01-24 13:35:10,453 - Persepolis - ERROR - Aria2 didn't respond!

2021-01-24 13:35:10,917 - Persepolis - ERROR - Download failed - GID : a1c261054834b1f8- Message : The response status is not successful. status=403

2021-01-24 13:35:12,802 - Persepolis - INFO - a1c261054834b1f8 Starts

2021-01-24 13:35:13,402 - Persepolis - ERROR - Download failed - GID : a1c261054834b1f8- Message : The response status is not successful. status=403

**Comment by rofibins** [comment]
OK its not persepolis's issue or bug wlwlwllwlwl
i found this https://grungeek.com/fix-http-403-404-error-in-free-download-manager/
that occurs because of my download link was expired so it becomes forbidden and unable to continue 
just try to download it again and paste on add new link at your persepolis and it will continue download the rest of your file

Closed

Regards,
