### ISSUE TITLE
ModuleNotFoundError: No module named 'PyQt5.sip

### ISSUE THREAD

**Issue by gerroon** [persepolisdm/persepolis#869]
**System Details:**
* Operating System:  Debian Testing
* Desktop Environment(For GNU/Linux and BSD users): Xfce
* Persepolis Version: I cant tell since it crashes
* How do you install Persepolis? (Repositories, source, ...)  I used the Ubuntu PPA

I seem to have Pyqt5.zip installed.

```
Traceback (most recent call last):
  File "/usr/bin/persepolis", line 33, in <module>
    sys.exit(load_entry_point('persepolis==3.0.1', 'console_scripts', 'persepolis')())
  File "/usr/bin/persepolis", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/persepolis/__main__.py", line 21, in <module>
    from persepolis.scripts import persepolis
  File "/usr/lib/python3/dist-packages/persepolis/scripts/persepolis.py", line 93, in <module>
    from persepolis.scripts import initialization
  File "/usr/lib/python3/dist-packages/persepolis/scripts/initialization.py", line 24, in <module>
    from PyQt5.QtCore import QSettings
ModuleNotFoundError: No module named 'PyQt5.sip'

```

```
sudo python3 setup.py install --record files.txt                                                                   
Linux detected!                                                                                                                                    
python3-pyqt5 is found                                                                                                                             
python3-requests is found!                                                                                                                         
python3-setproctitle is found!                                                                                                                     
python3-psutil is found!                                                                                                                           
youtube-dl is found                                                                                                                                
aria2 is found!                                                                                                                                    
libnotify-bin is found!                                                                                                                            
paplay is found!                                                                                                                                   
sound-theme-freedesktop is found!                                                                                                                  
ffmpeg is found!                                                                                                                                   
man page file is generated!                                                                                                                        
running install                                                                                                                                    
running bdist_egg                                                                                                                                  
running egg_info                                                                                                                                   
writing persepolis.egg-info/PKG-INFO                                                                                                               
writing dependency_links to persepolis.egg-info/dependency_links.txt                                                                               
writing entry points to persepolis.egg-info/entry_points.txt                                                                                       
writing top-level names to persepolis.egg-info/top_level.txt                                                                                       
reading manifest file 'persepolis.egg-info/SOURCES.txt'                                                                                            
writing manifest file 'persepolis.egg-info/SOURCES.txt'                                                                                            
installing library code to build/bdist.linux-x86_64/egg                                                                                            
running install_lib                                                                                                                                
running build_py                                                                                                                                   
creating build/bdist.linux-x86_64/egg                                                                                                              
creating build/bdist.linux-x86_64/egg/persepolis                                                                                                   
copying build/lib/persepolis/Persepolis Download Manager.py -> build/bdist.linux-x86_64/egg/persepolis                                             
copying build/lib/persepolis/__main__.py -> build/bdist.linux-x86_64/egg/persepolis                                                                
copying build/lib/persepolis/__init__.py -> build/bdist.linux-x86_64/egg/persepolis                                                                
creating build/bdist.linux-x86_64/egg/persepolis/constants                                                                                         
copying build/lib/persepolis/constants/Browser.py -> build/bdist.linux-x86_64/egg/persepolis/constants                                             
copying build/lib/persepolis/constants/Os.py -> build/bdist.linux-x86_64/egg/persepolis/constants                                                  
copying build/lib/persepolis/constants/__init__.py -> build/bdist.linux-x86_64/egg/persepolis/constants                                            
creating build/bdist.linux-x86_64/egg/persepolis/gui                                             
....
....


```

**Comment by alireza-amirsamimi** [comment]
Hello
This problem is related to PyQt5 Package in your distribution. Please report them this issue.

**Comment by alireza-amirsamimi** [comment]
In Arch Linux  python-pyqt5-sip package is dependency for python-pyqt5 package. Try to install this package.
Yo can also install PyQt5 with pip. It may solve the problem :)
