### ISSUE TITLE
Downloads do not complete (ADNI)

### ISSUE THREAD

**Issue by ccfas** [persepolisdm/persepolis#871]
**System Details:**
* Operating System: ?  **Windows 10**
* Distro(For GNU/Linux and BSD users): ? 
* Desktop Environment(For GNU/Linux and BSD users): ?
* Persepolis Version: ? **3.2.0**
* How do you install Persepolis? (Repositories, source, ...) **Installation Wiz**

**Issue Description and steps to reproduce:**

Hi, I having a big trouble to download some files from ADNI Database (http://adni.loni.usc.edu/). When any file reaches 99% completion I get any random error, file mismatch, socket error or simple disconnection error. Probably it´s not Persepolis problem, however if you know **anything (Setup/Config)** that I try to download it properly please, let me known! I already try to limit connections to 1... 

Congrats for you download manager, it was the only one that I could get at least almost something from that database, I will use for all my downloads from now!

Best R

#### Please report only one Issue (Bug or feature request or ...) in one issue! and open new Issue for another one :)

* _Please attach log files if crash or paste error message_

![image](https://user-images.githubusercontent.com/37549712/123994239-8f2e3980-d9a3-11eb-90b2-426790515fa7.png)

2021-06-30 05:00:27,018 - Persepolis - ERROR - Download failed - GID : e27c100ac4e08185- Message : Error
2021-06-30 05:00:59,875 - Persepolis - INFO - 62b21fb891859b98 Starts
2021-06-30 05:04:09,304 - Persepolis - ERROR - Spider couldn't find file name
2021-06-30 05:04:09,304 - Persepolis - ERROR - Spider couldn't find file size
2021-06-30 05:04:23,219 - Persepolis - ERROR - Spider couldn't find file name
2021-06-30 05:04:23,219 - Persepolis - ERROR - Spider couldn't find file size
2021-06-30 05:05:27,509 - Persepolis - ERROR - Spider couldn't find file name
2021-06-30 05:05:27,509 - Persepolis - ERROR - Spider couldn't find file size
2021-06-30 05:32:05,080 - Persepolis - ERROR - Download failed - GID : 62b21fb891859b98- Message : No URI available.
2021-06-30 05:53:06,059 - Persepolis - INFO - 1a75131b5870e976 Starts
2021-06-30 05:58:50,748 - Persepolis - ERROR - Download failed - GID : 1a75131b5870e976- Message : No URI available.
2021-06-30 06:01:14,610 - Persepolis - INFO - 1a17ded943fc4c44 Starts
2021-06-30 06:03:35,481 - Persepolis - ERROR - Download failed - GID : 1a17ded943fc4c44- Message : No URI available.
2021-06-30 06:04:27,144 - Persepolis - ERROR - Download did not start
2021-06-30 06:04:27,144 - Persepolis - ERROR - Traceback (most recent call last):
  File "persepolis\scripts\download.py", line 284, in downloadAria
  File "xmlrpc\client.py", line 1112, in __call__
  File "xmlrpc\client.py", line 1452, in __request
  File "xmlrpc\client.py", line 1154, in request
  File "xmlrpc\client.py", line 1166, in single_request
  File "xmlrpc\client.py", line 1272, in send_request
  File "http\client.py", line 1108, in putrequest
http.client.CannotSendRequest: Request-sent

2021-06-30 06:04:27,546 - Persepolis - ERROR - Download failed - GID : e68e96b8e75b0ab3- Message : Error
2021-06-30 06:04:47,879 - Persepolis - INFO - f23b50678bdf8750 Starts
2021-06-30 06:06:19,693 - Persepolis - ERROR - Download failed - GID : f23b50678bdf8750- Message : No URI available.
2021-06-30 07:29:11,841 - Persepolis - ERROR - Download failed - GID : 32f471bc2fb48e04- Message : No URI available.
2021-06-30 07:40:12,810 - Persepolis - INFO - efa861ac27550ad2 Starts
2021-06-30 07:42:02,582 - Persepolis - ERROR - Download failed - GID : efa861ac27550ad2- Message : No URI available.
2021-06-30 07:42:48,071 - Persepolis - INFO - 31bddee78276200c Starts
2021-06-30 07:44:08,343 - Persepolis - ERROR - Download failed - GID : 31bddee78276200c- Message : No URI available.
2021-06-30 07:45:01,754 - Persepolis - INFO - 33a505f1bce5c6e9 Starts
2021-06-30 07:47:11,430 - Persepolis - ERROR - Download failed - GID : 33a505f1bce5c6e9- Message : No URI available.
2021-06-30 07:48:00,922 - Persepolis - INFO - a2bbb8698ca46a7e Starts
2021-06-30 07:48:32,642 - Persepolis - INFO - None stopped
2021-06-30 07:48:32,871 - Persepolis - INFO - Download stoped - GID : a2bbb8698ca46a7e
2021-06-30 07:49:07,337 - Persepolis - INFO - 7db16d071cbdeb3b Starts
2021-06-30 07:49:25,664 - Persepolis - INFO - None stopped
2021-06-30 07:49:25,881 - Persepolis - INFO - Download stoped - GID : 7db16d071cbdeb3b
2021-06-30 07:50:37,437 - Persepolis - INFO - 87c5335a0bf609a8 Starts
2021-06-30 07:52:20,062 - Persepolis - INFO - 84de0131bb2d968a Starts
2021-06-30 07:52:47,887 - Persepolis - ERROR - Download failed - GID : 87c5335a0bf609a8- Message : No URI available.
2021-06-30 07:53:25,550 - Persepolis - INFO - 7af0812187fb6cf6 Starts
2021-06-30 07:58:21,265 - Persepolis - ERROR - Spider couldn't find file name
2021-06-30 07:58:21,265 - Persepolis - ERROR - Spider couldn't find file size
2021-06-30 07:58:42,769 - Persepolis - ERROR - Download failed - GID : 7af0812187fb6cf6- Message : Timeout.
2021-06-30 08:00:17,557 - Persepolis - INFO - 9d13a607f6feb65c Starts
2021-06-30 08:05:15,590 - Persepolis - ERROR - Spider couldn't find file name
2021-06-30 08:05:15,590 - Persepolis - ERROR - Spider couldn't find file size
2021-06-30 08:06:33,463 - Persepolis - ERROR - Download failed - GID : 9d13a607f6feb65c- Message : Timeout.
2021-06-30 08:21:56,557 - Persepolis - ERROR - Download failed - GID : 84de0131bb2d968a- Message : Size mismatch Expected:8579717275 Actual:0
2021-06-30 08:22:06,575 - Persepolis - ERROR - Download failed - GID : acacd143788e70a8- Message : No URI available.
2021-06-30 08:25:27,076 - Persepolis - INFO - 1ebc6545aa94a977 Starts
2021-06-30 08:27:38,182 - Persepolis - ERROR - Download failed - GID : 1ebc6545aa94a977- Message : No URI available.
2021-06-30 08:28:04,378 - Persepolis - INFO - 8831cf8d58ce7017 Starts
2021-06-30 08:30:04,887 - Persepolis - INFO - 69fc52816414043a Starts
2021-06-30 08:35:00,420 - Persepolis - ERROR - Spider couldn't find file name
2021-06-30 08:35:00,420 - Persepolis - ERROR - Spider couldn't find file size
2021-06-30 08:35:51,066 - Persepolis - ERROR - Download failed - GID : 8831cf8d58ce7017- Message : No URI available.
2021-06-30 08:49:22,813 - Persepolis - INFO - 42a8e7479010cbba Starts
2021-06-30 08:51:32,425 - Persepolis - ERROR - Download failed - GID : 42a8e7479010cbba- Message : No URI available.
2021-06-30 09:00:16,448 - Persepolis - INFO - 923b2f3685a93509 Starts
2021-06-30 09:04:33,605 - Persepolis - ERROR - Download failed - GID : 923b2f3685a93509- Message : Size mismatch Expected:24633096202 Actual:0
2021-06-30 09:05:14,275 - Persepolis - INFO - 442602eddb7c401b Starts
2021-06-30 09:05:15,802 - Persepolis - INFO - Download complete - GID : 442602eddb7c401b
2021-06-30 09:05:16,078 - Persepolis - ERROR - Spider couldn't find file name
2021-06-30 09:05:16,078 - Persepolis - ERROR - Spider couldn't find file size
2021-06-30 09:05:48,195 - Persepolis - INFO - ef1092d9661c8621 Starts
2021-06-30 09:07:25,909 - Persepolis - INFO - 9fde37216f3704ea Starts
2021-06-30 09:10:46,506 - Persepolis - ERROR - Spider couldn't find file name
2021-06-30 09:10:46,506 - Persepolis - ERROR - Spider couldn't find file size
2021-06-30 09:12:24,724 - Persepolis - ERROR - Spider couldn't find file name
2021-06-30 09:12:24,724 - Persepolis - ERROR - Spider couldn't find file size
2021-06-30 09:13:21,821 - Persepolis - ERROR - Download failed - GID : ef1092d9661c8621- Message : No URI available.
2021-06-30 09:21:21,540 - Persepolis - ERROR - Download failed - GID : 9fde37216f3704ea- Message : No URI available.
2021-06-30 10:10:16,201 - Persepolis - ERROR - Download failed - GID : 69fc52816414043a- Message : No URI available.
2021-06-30 11:28:44,704 - Persepolis - INFO - 27bc507de9014ee3 Starts
2021-06-30 11:30:30,981 - Persepolis - INFO - 3b626bccba485dd6 Starts
2021-06-30 11:31:27,867 - Persepolis - INFO - 61b74a285ed49c60 Starts
2021-06-30 11:33:43,266 - Persepolis - ERROR - Spider couldn't find file name
2021-06-30 11:33:43,266 - Persepolis - ERROR - Spider couldn't find file size
2021-06-30 11:35:06,761 - Persepolis - ERROR - Download failed - GID : 27bc507de9014ee3- Message : No URI available.
2021-06-30 11:38:30,573 - Persepolis - INFO - 23966d5abeae9352 Starts
2021-06-30 11:38:40,065 - Persepolis - ERROR - Spider couldn't find file name
2021-06-30 11:38:40,066 - Persepolis - ERROR - Spider couldn't find file size
2021-06-30 11:45:15,077 - Persepolis - ERROR - Download failed - GID : 23966d5abeae9352- Message : Network problem has occurred. cause:Unknown socket error 10060 (0x274c)
2021-06-30 11:50:26,107 - Persepolis - ERROR - Download failed - GID : 61b74a285ed49c60- Message : No URI available.
2021-06-30 12:31:54,344 - Persepolis - INFO - 6c6aa6757766ad3c Starts
2021-06-30 12:32:33,764 - Persepolis - ERROR - Download failed - GID : 3b626bccba485dd6- Message : Size mismatch Expected:61085070476 Actual:0
2021-06-30 12:32:55,018 - Persepolis - INFO - 75015b17e92944e7 Starts
2021-06-30 12:34:17,125 - Persepolis - INFO - 5ffacdbac12ead11 Starts
2021-06-30 12:34:31,758 - Persepolis - ERROR - Download failed - GID : 6c6aa6757766ad3c- Message : No URI available.
2021-06-30 12:35:53,872 - Persepolis - INFO - 7f9eeb45a59f2f3f Starts
2021-06-30 12:36:16,419 - Persepolis - INFO - None stopped
2021-06-30 12:36:33,146 - Persepolis - INFO - None stopped
2021-06-30 12:36:33,897 - Persepolis - INFO - Download stoped - GID : 75015b17e92944e7
2021-06-30 12:36:34,418 - Persepolis - INFO - Download stoped - GID : 5ffacdbac12ead11
2021-06-30 12:37:59,233 - Persepolis - INFO - 9647ca9469a57fec Starts
2021-06-30 12:38:17,233 - Persepolis - ERROR - Download failed - GID : 7f9eeb45a59f2f3f- Message : No URI available.
2021-06-30 12:39:24,609 - Persepolis - INFO - bfcf8d9e5c4cee57 Starts
2021-06-30 12:40:19,467 - Persepolis - INFO - 6aa9e2336e948f25 Starts
2021-06-30 12:40:21,980 - Persepolis - ERROR - Download failed - GID : 9647ca9469a57fec- Message : Size mismatch Expected:24633096202 Actual:0
2021-06-30 12:40:33,268 - Persepolis - INFO - eec8a99a7897c479 Starts
2021-06-30 12:41:13,212 - Persepolis - ERROR - Download failed - GID : bfcf8d9e5c4cee57- Message : Size mismatch Expected:8579717275 Actual:0
2021-06-30 12:41:46,193 - Persepolis - INFO - None stopped
2021-06-30 12:41:46,193 - Persepolis - ERROR - Aria2 didn't respond!
2021-06-30 12:41:48,212 - Persepolis - INFO - Reconnecting Aria2 ...
2021-06-30 12:41:48,212 - Persepolis - INFO - Persepolis reconnected aria2 successfully
2021-06-30 12:41:48,234 - Persepolis - ERROR - Download did not start
2021-06-30 12:41:48,234 - Persepolis - ERROR - Traceback (most recent call last):
  File "persepolis\scripts\download.py", line 284, in downloadAria
  File "xmlrpc\client.py", line 1112, in __call__
  File "xmlrpc\client.py", line 1452, in __request
  File "xmlrpc\client.py", line 1154, in request
  File "xmlrpc\client.py", line 1170, in single_request
  File "xmlrpc\client.py", line 1342, in parse_response
  File "xmlrpc\client.py", line 656, in close
xmlrpc.client.Fault: <Fault 1: 'No URI to download.'>

2021-06-30 12:41:48,434 - Persepolis - INFO - Download stoped - GID : eec8a99a7897c479
2021-06-30 12:43:23,642 - Persepolis - INFO - 1e818b04c3df78da Starts
2021-06-30 12:44:12,992 - Persepolis - ERROR - Download failed - GID : 1e818b04c3df78da- Message : No URI available.
2021-06-30 12:45:17,626 - Persepolis - ERROR - Spider couldn't find file name
2021-06-30 12:45:17,626 - Persepolis - ERROR - Spider couldn't find file size
2021-06-30 12:45:29,046 - Persepolis - ERROR - Spider couldn't find file name
2021-06-30 12:45:29,046 - Persepolis - ERROR - Spider couldn't find file size
![image](https://user-images.githubusercontent.com/37549712/123997265-97d43f00-d9a6-11eb-836f-4b6f26fb90df.png)

**Comment by ccfas** [comment]
![image](https://user-images.githubusercontent.com/37549712/123997059-580d5780-d9a6-11eb-9f4c-7ad77f0899f3.png)

**Comment by ccfas** [comment]
Persepolis Download Manager, 2021/06/30 22:43:00

2021-06-30 22:43:00,123 - Persepolis - INFO - chrome: Json file is created successfully.
2021-06-30 22:43:00,128 - Persepolis - INFO - chromium: Json file is created successfully.
2021-06-30 22:43:00,128 - Persepolis - INFO - opera: Json file is created successfully.
2021-06-30 22:43:00,128 - Persepolis - INFO - vivaldi: Json file is created successfully.
2021-06-30 22:43:00,128 - Persepolis - INFO - firefox: Json file is created successfully.
2021-06-30 22:43:01,274 - Persepolis - INFO - youtube_dl version: 2019.09.12.1
2021-06-30 22:43:02,169 - Persepolis - INFO - 
**********
ffmpeg version 4.2 Copyright (c) 2000-2019 the FFmpeg developers
built with gcc 9.1.1 (GCC) 20190807  configuration: --enable-gpl
--enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls
--enable-iconv --enable-libass --enable-libdav1d --enable-libbluray
--enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb
--enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus
--enable-libshine --enable-libsnappy --enable-libsoxr --enable-
libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack
--enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2
--enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-
libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-
libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-
libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va
--enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth
--enable-libopenmpt  libavutil      56. 31.100 / 56. 31.100
libavcodec     58. 54.100 / 58. 54.100  libavformat    58. 29.100 /
58. 29.100  libavdevice    58.  8.100 / 58.  8.100  libavfilter     7.
57.100 /  7. 57.100  libswscale      5.  5.100 /  5.  5.100
libswresample   3.  5.100 /  3.  5.100  libpostproc    55.  5.100 /
55.  5.100
**********
2021-06-30 22:43:02,169 - Persepolis - INFO - python version: 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
2021-06-30 22:43:02,169 - Persepolis - INFO - QT version: 5.13.1
2021-06-30 22:43:02,169 - Persepolis - INFO - PyQt version: 5.13.1
2021-06-30 22:43:02,169 - Persepolis - INFO - Operating system: Windows
2021-06-30 22:43:03,963 - Persepolis - ERROR - Aria2 didn't respond!
2021-06-30 22:43:03,963 - Persepolis - INFO - Starting Aria2
2021-06-30 22:43:06,011 - Persepolis - INFO - Aria2 is running
2021-06-30 22:43:06,011 - Persepolis - INFO - Aria2 version: 1.34.0
2021-06-30 22:43:48,692 - Persepolis - INFO - a60a52b877c07a53 Starts
2021-06-30 22:45:04,147 - Persepolis - INFO - 58d227c354bdf371 Starts
2021-06-30 22:46:10,323 - Persepolis - ERROR - Download failed - GID : a60a52b877c07a53- Message : No URI available.
2021-06-30 22:46:59,347 - Persepolis - INFO - f8fa20df78543bd9 Starts
2021-06-30 22:50:00,519 - Persepolis - ERROR - Spider couldn't find file name
2021-06-30 22:50:00,519 - Persepolis - ERROR - Spider couldn't find file size
2021-06-30 22:51:22,214 - Persepolis - INFO - ac184278bf480419 Starts
2021-06-30 22:51:59,041 - Persepolis - ERROR - Spider couldn't find file name
2021-06-30 22:51:59,041 - Persepolis - ERROR - Spider couldn't find file size
2021-06-30 22:54:01,079 - Persepolis - ERROR - Download failed - GID : 58d227c354bdf371- Message : No URI available.
2021-06-30 22:55:33,673 - Persepolis - ERROR - Download failed - GID : f8fa20df78543bd9- Message : Timeout.
2021-06-30 22:56:20,887 - Persepolis - ERROR - Spider couldn't find file name
2021-06-30 22:56:20,887 - Persepolis - ERROR - Spider couldn't find file size
2021-06-30 22:56:36,256 - Persepolis - ERROR - Download failed - GID : ac184278bf480419- Message : Size mismatch Expected:8579717275 Actual:0
2021-06-30 22:57:30,403 - Persepolis - INFO - 32be1ad2f5a67291 Starts

**Comment by ccfas** [comment]
Today I just tried to opened the files anyway and it opened! So even the program shows 99% of completion all files were downloaded properly!

**Comment by MortezaH66** [comment]
Hi!
Same problem in :
Ubuntu 20.04 LTS .
Latest Update of perse-police .
downloading process is ended , but program is shows 99% .
it have no problem to stop and resum download again for 100 .
but when we make a Queue and start it ..
after a long time it stops on first file in list and 99% without any change !
