### ISSUE TITLE
مشکل با نسخه ۲.۳ بعد از آپدیت

### ISSUE THREAD

**Issue by molaeiali** [persepolisdm/persepolis#88]
فایل کانفیگ رو پاک کردم همونطور که اخطار دادید ولی بعد از اجرا اینو می‌گیرم

```
~$ persepolis 
Traceback (most recent call last):
  File "/usr/share/persepolis/persepolis", line 40, in <module>
    from mainwindow import MainWindow
  File "/usr/share/persepolis/mainwindow.py", line 26, in <module>
    from text_queue import TextQueue
  File "/usr/share/persepolis/text_queue.py", line 25, in <module>
    import spider
  File "/usr/share/persepolis/spider.py", line 17, in <module>
    import requests 
ModuleNotFoundError: No module named 'requests'
```

**Comment by mavahedinia** [comment]
@molaeiali خب این میگه که python-requests ندارین! دستی نصب کنین الان درستش می‌کنیم!

**Comment by molaeiali** [comment]
@Mr0Null آره با نصبش حل شد

فکر کنم باید به وابستگیاش توی AUR اضافه کنید این بسته رو تا خودکار زمان آپدیت نصب بشه

**Comment by alireza-amirsamimi** [comment]
سلام ممنونم از اطلاعتون
مشکل حل شد
