### ISSUE TITLE
Persepolis doesn't start in Manjaro KDE..

### ISSUE THREAD

**Issue by rafidalhaque** [persepolisdm/persepolis#916]
**System Details:**
* Operating System: **Linux**
* Distro(For GNU/Linux and BSD users): **Manjaro**
* Desktop Environment(For GNU/Linux and BSD users): **KDE**
* Persepolis Version: **_[Download from official manjaro repo. don't know]_**
* How do you install Persepolis? (Repositories, source, ...)
**_Official Manjaro Repository_**
* _Please attach log files if crash or paste error message_
```bash
$ persepolis                                                                                 
Traceback (most recent call last):
  File "/usr/bin/persepolis", line 33, in <module>
    sys.exit(load_entry_point('persepolis==3.2.0', 'console_scripts', 'persepolis')())
  File "/usr/bin/persepolis", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/persepolis/__main__.py", line 20, in <module>
    from persepolis.scripts import persepolis
  File "/usr/lib/python3.10/site-packages/persepolis/scripts/persepolis.py", line 93, in <module>
    from persepolis.scripts.mainwindow import MainWindow
  File "/usr/lib/python3.10/site-packages/persepolis/scripts/mainwindow.py", line 26, in <module>
    from persepolis.scripts.setting import PreferencesWindow
  File "/usr/lib/python3.10/site-packages/persepolis/scripts/setting.py", line 18, in <module>
    from persepolis.gui.setting_ui import Setting_Ui, KeyCapturingWindow_Ui
  File "/usr/lib/python3.10/site-packages/persepolis/gui/setting_ui.py", line 22, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```
**steps to reproduce:**
1. Install from official repo by
```
sudo pacman -S persepolis
```
2. Run ```persepolis``` command.

**Comment by ZoidMonster** [comment]
I have had this problem on and off since I started using it about a year ago.  I don't know any other way to describe it but that sometimes it works sometimes it doesn't, that is without updating or making any changes at all to the system (Arch Linux KDE Plasma) in between uses, the only factor being it always happens after using it once or any number of times, and closing it completely (So also the systrey applet).  Sometimes a reboot helps, sometimes it doesn't.

Then when it does launch, it's a craps shoot if it will find the media or not, pasting the link in vs it finding it by itself makes no difference, and every time I want to use it, all I can do is cross my fingers, because it's random, and there's no indication or reason what the cause may be, and I don't know where or how to check logs and such, nor is it explained here or on the programs main site, which it definitely should as often as problems occur.  Also when opening a Youtube page with a playlist, again, it may or may not work at all, or only finds the 1st video: so far it has never found the rest of the videos in the list, only the first one.  It feels like Persepolis is breaking itself somehow!

Nowhere can I find any information on why it sometimes does and other times doesn't find the media, and whether it's related to Youtube, Firefox or Persepolis.  It also makes no difference whether the media is expected to be protected by YouTube or DRM (movie or music), or not (Instructional video).

One thing I can say for sure is that this project is plagued with problems that just keep reoccurring at random, and every time I think it's fixed it's just a matter of time until it breaks again, and that time can be as short as an hour between uses.  It's a great program when it does work, but that is defeated by the fact that it all too often just doesn't.
