### ISSUE TITLE
App not working!

### ISSUE THREAD

**Issue by alr86** [persepolisdm/persepolis#928]
**System Details:**
* Linux mint 21.1
* Plasma 5.24.7 
* I am installing Persepolis from repo

`/usr/lib/python3/dist-packages/persepolis/scripts/check_proxy.py:156: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if mac_tmp_proxies_list['SOCKSEnable'] is '1':
Traceback (most recent call last):
  File "/usr/bin/persepolis", line 11, in <module>
    load_entry_point('persepolis==3.2.0', 'console_scripts', 'persepolis')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 479, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2861, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2465, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2471, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/persepolis/__main__.py", line 20, in <module>
    from persepolis.scripts import persepolis
  File "/usr/lib/python3/dist-packages/persepolis/scripts/persepolis.py", line 93, in <module>
    from persepolis.scripts.mainwindow import MainWindow
  File "/usr/lib/python3/dist-packages/persepolis/scripts/mainwindow.py", line 38, in <module>
    from PyQt5.Qt import PYQT_VERSION_STR
ImportError: cannot import name 'PYQT_VERSION_STR' from 'PyQt5.Qt' (/usr/local/lib/python3.10/dist-packages/PyQt5/Qt.abi3.so)
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_bin_persepolis.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/persepolis", line 11, in <module>
    load_entry_point('persepolis==3.2.0', 'console_scripts', 'persepolis')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 479, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2861, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2465, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2471, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/persepolis/__main__.py", line 20, in <module>
    from persepolis.scripts import persepolis
  File "/usr/lib/python3/dist-packages/persepolis/scripts/persepolis.py", line 93, in <module>
    from persepolis.scripts.mainwindow import MainWindow
  File "/usr/lib/python3/dist-packages/persepolis/scripts/mainwindow.py", line 38, in <module>
    from PyQt5.Qt import PYQT_VERSION_STR
ImportError: cannot import name 'PYQT_VERSION_STR' from 'PyQt5.Qt' (/usr/local/lib/python3.10/dist-packages/PyQt5/Qt.abi3.so)
`

**Comment by Alirezaies** [comment]
Hi there, before continuing on this issue, we have major updates, did you try installing latest version of Persepolis Download Manager?

**Comment by alr86** [comment]
That's fixed!👍️
