### ISSUE TITLE
App not working 

### ISSUE THREAD

**Issue by r0hanchaulagain** [persepolisdm/persepolis#929]
**System Details:**
* Operating System: 6.1.12-1-MANJARO 
* Distro(For GNU/Linux and BSD users): Arch Linux
* Desktop Environment(For GNU/Linux and BSD users): KDE plasma
* Persepolis Version: 3.2.0
* How do you install Persepolis? (Repositories, source, ...)   --> via github repo 

*
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/persepolis-3.2.0-py3.11.egg/persepolis/scripts/persepolis.py", line 17, in <module>
ModuleNotFoundError: No module named 'PySide6'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/persepolis", line 33, in <module>
    sys.exit(load_entry_point('persepolis==3.2.0', 'console_scripts', 'persepolis')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/persepolis", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.11/site-packages/persepolis-3.2.0-py3.11.egg/persepolis/__main__.py", line 20, in <module>
  File "/usr/local/lib/python3.11/site-packages/persepolis-3.2.0-py3.11.egg/persepolis/scripts/persepolis.py", line 21, in <module>
ModuleNotFoundError: No module named 'PyQt5'
 
 pamac install python-pyqt5                                                                                                                                                                                                1 ✘ 
Preparing...
Warning: python-pyqt5-5.15.9-1 is up to date -- skipping
Nothing to do.
Transaction successfully finished.

 ~  pamac install pyside6                                                                                                                                                                                                        ✔ 
Preparing...
Warning: pyside6-6.4.2-5 is up to date -- skipping
Nothing to do.
Transaction successfully                                  

**Issue Description and steps to reproduce:**
nothing, i just downloaded and installed as said in the insatallation guide of the repo, but after install, i open the app, it didnt open and upon trying open from terminal, i got the above error, i also tried installing the modules it said to be missing but i already have them installed as said. Plz help

**Comment by khaled-0** [comment]
It might be hardcoded module import
try installing with
```
sudo pip3 install PyQt5
```

**Comment by Alirezaies** [comment]
Hi there, before continuing on this issue, we have major updates, did you try installing latest version of Persepolis Download Manager?
