### ISSUE TITLE
crash instanly after open pdm after update ubuntu 2023

### ISSUE THREAD

**Issue by saeedhpro** [persepolisdm/persepolis#937]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/persepolis/scripts/persepolis.py", line 400, in main
    mainwindow = MainWindow(start_in_tray, persepolis_download_manager, persepolis_download_manager.setting)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/persepolis/scripts/mainwindow.py", line 926, in __init__
    dict = download_table_dict[gid]
           ~~~~~~~~~~~~~~~~~~~^^^^^
KeyError: '97d71a0f387dd5f4'

**Comment by mostafaasadi** [comment]
would you please update to latest version and recheck again?
