### ISSUE TITLE
Failure to intercept download on Win 10 using Edge

### ISSUE THREAD

**Issue by wlkoerner** [persepolisdm/persepolis#968]
**System Details:**
* Operating System: Win 10
* Browser and version: Microsoft Edge Version 123.0.2420.81 (Official build) (64-bit)
* Distro(For GNU/Linux and BSD users): ?
* Desktop Environment(For GNU/Linux and BSD users): ?
* Persepolis Version: 4.01
* How do you install Persepolis? (Repositories, source, ...)
 Desktop from the repository; browser extension from the Web Store
* _Please attach log files if crash or paste error message_

Traceback (most recent call last):
  File "persepolis\Persepolis Download Manager.py", line 21, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "persepolis\scripts\persepolis.py", line 212, in <module>
struct.error: unpack requires a buffer of 4 bytes

**Issue Description and steps to reproduce:**

Just attempt a download with the Persepolis desktop and browser extension active.

**Comment by alireza-amirsamimi** [comment]
Hello
We haven't tested the Persepolis browser extension for Microsoft Edge yet, and we're not sure if it works or not. We released extension for FireFox and Chrome. We will try and let you know.
